### ISSUE TITLE
Can a toggle be implemented as a checkbox?

### ISSUE THREAD

**Issue by mbgower** [w3c/aria-practices#1016]
I'm working with a new library and the toggle button has been implemented as a checkbox. The authoring practices guide states:
> Toggle button: A two-state button that can be either off (not pressed) or on (pressed). To tell assistive technologies that a button is a toggle button, specify a value for the attribute aria-pressed. For example, a button labeled mute in an audio player could indicate that sound is muted by setting the pressed state true. Important: it is critical the label on a toggle does not change when its state changes. In this example, when the pressed state is true, the label remains "Mute" so a screen reader would say something like "Mute toggle button pressed". Alternatively, if the design were to call for the button label to change from "Mute" to "Unmute," the aria-pressed attribute would not be needed.

and later says:
> If the button is a toggle button, it has an aria-pressed state. When the button is toggled on, the value of this state is true, and when toggled off, the state is false.

However, I note that one of your working examples uses an anchor behind the scenes:
<code>&lt;a tabindex="0" role="button" id="toggle" aria-pressed="false"&gt;
          Mute
          &lt;svg&gt;
            &lt;use xlink:href="images/mute.svg#icon-sound"&gt;&lt;/use&gt;
          &lt;/svg&gt;
        &lt;/a&gt;
</code>

Is using a checkbox behind the scenes considered a failure? Is the difference in keyboard operation enough to make it unacceptable?

> Dual-state: The most common type of checkbox, it allows the user to toggle between two choices -- checked and not checked.

**Comment by patrickhlauke** [comment]
>I note that one of your working examples uses an anchor behind the scenes [...] is the difference in keyboard operation enough to make it unacceptable?

The example buttons https://www.w3.org/TR/wai-aria-practices-1.1/examples/button/button.html have extra scripting that makes them work both for `Space` and `Enter`

> Is using a checkbox behind the scenes considered a failure? 

a failure of ... WCAG you mean (since ARIA / ARIA Practices don't do pass/fails)? or more "would this go against best practice"?

personally, I would posit that it can be slightly confusing (and verbose) for AT users to hear "Sound, checkbox, checked" / "Sound, checkbox, not checked", but probably not a complete blocker for users to understand what's going on. However, if the author also changes the text, then it becomes problematic (e.g. "Mute, checkbox, checked" vs "Unmute, checkbox, checked" - or vice-versa regarding the checkedness ... in any case, it'll be unclear what is meant/what the effect of checking/unchecking is...it the label describing the current state, or what will happen if i check/uncheck).

**Comment by mbgower** [comment]
Thanks for the perspective @patrickhlauke. Sure, I meant  'go against best practice' rather than failure. I've had too much WCAG on my mind lately :)

"Mute toggle button pressed" is actually a little more verbose than "Mute checkbox, checked", but I certainly take your point on how confusing it would be if the text were to change. That is also a  problem with a button as well, hence the
> Important: it is critical the label on a toggle does not change when its state changes. 

So in the same way you wouldn't want an aria-pressed attribute with a changing label, you wouldn't want to allow a changed label for an implementation with checkbox in the background.

That said, I think I'm happy advising them that implementing as a button is less prone to error than as a checkbox. I'll also be sure to capture the different implementation considerations if they alter the label in response to the user action. Thanks!
