### ISSUE TITLE
Avoid using "HTML5" (say "HTML" instead)

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-practices#1020]
I think it's not useful anymore to talk about "HTML5", for a couple of reasons:

* People are not using HTML4 anymore; things like `aside` are not new.
* The [HTML standard](https://html.spec.whatwg.org/multipage/) does not call itself or talk about "HTML5".

Suggest to change it to "HTML".

**Comment by zcorpan** [comment]
cc @spectranaut

**Comment by carmacleod** [comment]
You may want to also add [HTML] to the references section at the end of the document.

**Comment by jnurthen** [comment]
@carmacleod the references section is generated automatically. If you use [[HTML]] once in the document it will appear.

**Comment by carmacleod** [comment]
Cool magic.  :)

Ok, please use [[HTML]] to add [HTML] to the references section.

Also consider using [HTML] here and there in the prose so that links to the reference are automatically generated as well. (Currently, all references to HTML in the APG seem to be just the text "HTML" without the square brackets).

Also, when changing all HTML5 to HTML, reminder to fix up the landmarks example, which has a tab for "HTML5" sectioning elements.

**Comment by jnurthen** [comment]
> Cool magic. :)
> 
> Ok, the APG needs to please use [[HTML]] to add [HTML] to the references section.
> 
> Also consider using [HTML] here and there in the prose so that links to the reference are automatically generated as well. (Currently, all references to HTML in the APG seem to be just the text "HTML" without the square brackets).
> 
> Also, when changing all HTML5 to HTML, reminder to fix up the landmarks example, which has a tab for "HTML5" sectioning elements.

Already done - see #1058

**Comment by carmacleod** [comment]
> Already done

Nice! You are way ahead of me!  :)
