### ISSUE TITLE
Open aria practice's examples in online javascript/html/css editor

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1102]
See draft PR #1110 for an example implementation using Codepen's [post API](https://blog.codepen.io/documentation/api/prefill/).

See draft PR #1111 for an example implementation using JSFiddle's [post API](https://docs.jsfiddle.net/api/display-a-fiddle-from-post)

We'd really like to hear from the community if they prefer JSFiddle or Codepen, it seems like both are perfectly workable solutions from the tech side.

**Comment by mcking65** [comment]
@zcorpan, we are going with the codepen implementation in PR #1110.

However, instead of manually adding the button to open codepen to each example page, we would like to add it dynamically. The examples/js/examples.js script runs on every example page to add the HTML source of the example. We can add this capability to that script.

I'm assigning this issue to you to make that change to examples.js.
