### ISSUE TITLE
Authoring Practices Guide entry for role searchbox

### ISSUE THREAD

**Issue by 0ddfell0w** [w3c/aria-practices#1115]
Is there a plan to provide guidance for authoring ARIA searchboxes?

**Comment by carmacleod** [comment]
There is already a search section and example in the APG. It's in the landmarks section.
Guidance: http://w3c.github.io/aria-practices/#aria_lh_search
Example: http://w3c.github.io/aria-practices/examples/landmarks/search.html

Also, in case it's helpful, there's a search example being developed in the Web Accessibility Tutorials:
https://w3c.github.io/wai-tutorials/ideas/search/

Feedback welcome!

**Comment by carmacleod** [comment]
@0ddfell0w Is it ok to close this issue? Do the above examples provide enough guidance?

**Comment by 0ddfell0w** [comment]
@carmacleod Makes sense. I was just surprised to only see `searchbox` referenced in the combobox pattern. Is that the primary use case for the role? If so, closing this issue seems reasonable and I thank you for the clarification!

**Comment by 0ddfell0w** [comment]
Quick FYI that this link is broken https://w3c.github.io/wai-tutorials/ideas/search/

**Comment by jnurthen** [comment]
> Quick FYI that this link is broken https://w3c.github.io/wai-tutorials/ideas/search/

If still down please log in the wai-tutorials repository not here.

**Comment by jnurthen** [comment]
> > Quick FYI that this link is broken https://w3c.github.io/wai-tutorials/ideas/search/
> 
> If still down please log in the wai-tutorials repository not here.

Sorry - read the thread again and noticed @carmacleod had referenced that example.

**Comment by mcking65** [comment]
First note that role searchbbox is a textbox whereas role search is a landmark region. They are not at all the same thing.

Since a searchbox is a textbox, it is not clear how a combobox can be a searchbox. We will talk about this at TPAC. What would a screen reader call it? A combosearchbox?????

So far, I have not found a use for the searchbox role. It describes an ordinary text box that is used for entering a search term. Those are very rare on the web. Typically web search inputs have typeahead and a suggestion popup, so they are implemented as a combobox.

However, plain text boxes that are for search are common in native iOS apps. Just as with the switch role, I believe that was the driver for including it in ARIA 1.1. Perhaps there are people developing web apps that are intended to feel just like a native iOS app, and they need a role like this. To-date, we do not have any patterns intended to specifically mimic native iOS in the APG.

So, the net is that we do not yet have specific plans for searchbox guidance in the APG. And, it is possible that we will remove mention of searchbox from the combobox role definition and APG pattern.

**Comment by 0ddfell0w** [comment]
Opened related #1158 to discuss any additions to the combobox role, specific to comoboboxes that use searchbox

**Comment by mcking65** [comment]
@0ddfell0w, I think the answer to your original question here is that we do not yet know what kind of guidance we will provide for the searchbox role in the APG. Are you OK with closing this issue?

**Comment by 0ddfell0w** [comment]
Closing seems fine. #1158 can cover any of my questions re: using the searchbox role in the context of a combobox. Thanks for the clarifications!
