### ISSUE TITLE
Issues with tabs widget code example

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#114]
Some issues with the tabs widget code example:
- [x] When <kbd>home</kbd> or <kbd>end</kbd> is activated their default action isn’t prevented. (can only prevent those on keydown)
- [x] Can’t get to content with VoiceOver on iOS (tested on iOS 10)
- [x] Need normal content
- [x] Needs more explanation of what the script does
- [x] Code example title is wrong (mentions tablist twice)
- [x] Remove first `h2`
- [x] Pattern is misspelled
- [x] Remove note
- [x] Edit deletion description
- [x] Update tabs and panels arrays on deletion
- [x] Use new examples template
- [x] Investigate IE 11 issues Bryan brought up on the list
- [x] Remove delay

**Comment by mcking65** [comment]
Please update the page to use the 
[examples/coding-template/SingleImplementationExample-Template.html](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/SingleImplementationExample-Template.html).
An example page that implements the template is 
[Simple Two-State Checkbox Example](http://w3c.github.io/aria-practices/examples/checkbox/checkbox-1.html). 

Some of the items missing that are included in the template are:
* labeled landmark regions to bracket the example itself as well as the html source.
* a nav region at the end with a link back to the design pattern
* A format for the title tag

**Comment by mcking65** [comment]
Recommend deleting The first H2 with text: "Creating a tabs widget using role=tab, role=tablist, and role=tablist."

Pattern is misspelled in the first link with text "Authoring Practice Design Patten for Tabs".

I don't understand this note; I think it could be deleted?
"Note: When using HTML, use the <button> element for tabs. It is recommended that authors not re-purpose other elements to create buttons."
Looks like a slightly edited copy/paste from the button example.

In the keyboard table, it says:
"If deletion is allowed, deletes the current tab element and its associated tab panel."

Since delete is supported, recommend changing to:
"Deletes the current tab element and its associated tab panel."

In Firefox with JAWS, After delete is performed, JAWS and NVDA report incorrect setsize; this may be a Firefox bug. Requires investigation.

After delete, home/end do not work, and left/right do not wrap.

**Comment by MichielBijl** [comment]
All these issues are now fixed. They’re also pushed to master and a build succeeded (I don’t know how that happened).

I changed the line about deleting to:

“If deletion on the selected tab is allowed this will that tab element and its associated tab panel.”

That way you cover cases where not all tabs are deletable (which is actually the case in the code example).
