### ISSUE TITLE
Am I missing something or is there no Navigation menu in the new draft?

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#116]
It used to be called "navigator" in the old draft. Now I don't see anything for a mega navigation menu, hamburger menu, to navigate the the site that is part of the template on every page  ... etc...

I think it would be a major omission and would cause people to look at the "menu" widget instead for navigation.

**Comment by jnurthen** [comment]
The current plan is for this to be in the APG R2 milestone - https://github.com/w3c/aria-practices/milestone/3
If we could have help drafting it we could consider moving it to a closer release - but the group has limited bandwidth. Would you be prepared to help with this?

**Comment by mcking65** [comment]
The old site navigator sections, that I drafted a few years ago,  were far too difficult to understand and somewhat complicated. However, they didn't include either mega menus or hamburgers.

As James mentioned, we will have a set of patterns for site navigators. What is included is TBD.

BTW, is there a problem using the menubutton pattern for a hamburger menu? Isn't a hamburger just a particular kind of icon that opens a menu. And, isn't it an icon that has fallen out of favor due to its universal lack of clarity?

**Comment by DavidMacDonald** [comment]
I'm swamped with projects after taking a couple of weeks off for TPAC and vacation but in a month or so I hope to get more openings. I would be willing to take a shot at writing up a draft.
Regarding a hamburger icon. I'd say it's fairly universal right now, and well recognized. I don't think requiring the visible word "menu" with it or alone would be well accepted by industry.

**Comment by DavidMacDonald** [comment]
I started playing around with the previous Navigator text to look for ways to simplify it, without making unnecessary changes. What is the team's thought on the roles of "menu" and "menuitem". My sense is that those roles aren't necessary for a navigation mechanism. A group of anchors in `<li>` elements inside a container with `<nav>` I think is well understood by most screen readers.

**Comment by mcking65** [comment]
Closing because this is covered by #89
