### ISSUE TITLE
Clarify focus movement when a menuitem in a menubar is activated

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#120]
When reading text in the menu design pattern, it is unclear what should happen when focus is on the menuitem in a menu bar. Clarify whether space/enter should open the submenu or not.

**Comment by mcking65** [comment]
All, Please review the updated keyboard section of the 
[Menu or Menubar Design Pattern](http://w3c.github.io/aria-practices/#menu) and provide feedback by commenting on this issue.

**Comment by annabbott** [comment]
Fourth bullet under "Space": 
Current text: Optionally, activates the focused menuitem.
Suggested edit: Optionally, activates the focused menuitem and closes the menu.

Spatial orientation of "horizontal" and "vertical" for all arrow key navigation is very confusing and as currently written, I'd never be able to explain to design, dev and/or test. The second paragraph in the definition of menu/menubar states "A menubar is typically horizontal..." and both examples show horizontal menu/menubars. No example includes an original spatial oreintation of a vertical menu/menubar. In the arrow key navigation sections, each calls out a difference when navigating horizontal or vertical - is that difference related to the original spatial orientation of the menu/menubar? Or is that difference based on whether menuitems have a spatial orientation of horizontal or vertical?

These two statements currently exist:
Down
Otherwise, if the focused menuitem is in a horizontal submenu of a parent vertical menubar, closes the submenu and moves focus to the first menuitem contained in the submenu opened by the next menuitem in the parent menubar. 
Up
Otherwise, if the focused menuitem is in a horizontal submenu of a parent vertical menubar, moves focus to the first menuitem contained in the submenu opened by the previous menuitem in the parent menubar. 
Shouldn't both those statements state "...closes the submenu and moves focus to the first menuitem contained in the submenu opened by the next menuitem in the parent menubar. "
Both the right arrow and left arrow also include "...closes the submenu...".

Is the following statement required or optional?
Any key that corresponds to a printable character: Move focus to the next menu item in the current menu whose label begins with that printable character."

Your thoughts?

**Comment by mcking65** [comment]
@annabbot,

Good catches on the lack of optional for the type ahead and for the missing statements about closing menus when actions are performed.

With respect to spacial orientation and arrow key descriptions, in retrospect, I hated doing these edits as much as you are confused by them. The language is way too dense. As I try to follow your comments, I struggle with understanding. I have to make this better. I have an idea for another approach and will make a separate branch for it.

And, yes, we should have an example of a vertical menubar.

**Comment by mcking65** [comment]
Now compare these two versions:

1. [Option one in master branch in RawGit](https://rawgit.com/w3c/aria-practices/master/aria-practices.html#menu)
2. [Option two in menuKeyboardOption2 branch in RawGit](https://rawgit.com/w3c/aria-practices/menuKeyboardOption2/aria-practices.html#menu)

**Comment by a11ydoer** [comment]
@mcking65 @jongund @jnurthen @accdc 

[Option two in menuKeyboardOption2 branch in RawGit ](https://rawgit.com/w3c/aria-practices/menuKeyboardOption2/aria-practices.html#menu) is much clear for me and has cleared some of confusions. (I was the one who originally raised this issue in the APG meeting and James kindly got it recorded.)

However, "moves focus to **the parent menuitem** in the menubar" in the third list item in left arrow behavior description is not clear nor consistent in comparison with right arrow description. Do you mean "the parent menuitem" as first item of previous parent item?

**Comment by mcking65** [comment]
@a11ydoer 

Check it out now; I did some more revising of the description of right and left arrow keys.

**Comment by accdc** [comment]
The section looks clear to me in the APG.

**Comment by jnurthen** [comment]
Looks good to me

**Comment by mcking65** [comment]
I see enough consensus to merge option 2 into master, so I have done that and updated the note at the beginning of the keyboard section.
I will wait for a review by @annabbott before removing the note and closing this issue.

**Comment by annabbott** [comment]
Reviewed keyboard section of Menu (http://w3c.github.io/aria-practices/#menu) - MUCH clearer! As a matter of fact, it is now so clear that I'll probably never have to explain to Dev/Test!

**Comment by mbgower** [comment]
@mcking65 , the updates are much clearer. A trivial typo you may elect to ignore. In Note 1, "can not" should be one word "cannot".

**Comment by mcking65** [comment]
@mbgower  

Mike, thanks for the feedback! I fixed the mistake in 
commit 096593e77a10a64c44ba081e0905c42b4169bfbf
