### ISSUE TITLE
Space key and Selenium testing framework 

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#1358]
In the updated version of the Javascript for menubar-editor I switched from using `event.keyCode` to `event.key` property.   The testing script [menbar_menubar-navigator.js](https://github.com/w3c/aria-practices/blob/issue1355-update-menubar-editor-js/test/tests/menubar_menubar-editor.js) (line 500) has a test for the SPACE key and it was failing even though it worked with manual testing on the example.  So I added a couple lines of code in [menubar-editor.js](https://github.com/w3c/aria-practices/blob/issue1355-update-menubar-editor-js/examples/menubar/js/menubar-editor.js) to detect `event.keyCode === 32` and if this is true change `event.key` to equal ` ` (see line 524).   The test script now passed for all tests including the SPACE key test.  Seems to me a bug with Selenium, but maybe it is something I am doing.   

Test Files with "failing" tests due to the SPACE key issue:
* `/test/tests/combobox_datepicker.js`
* `/test/tests/dialog-modal-datepicker.js`
* `/test/tests/menubar_menubar-navigation.js`
* `/test/tests/menubar_menubar-editor.js`

**Comment by smhigley** [comment]
It appears there are known issues with GeckoDriver + Selenium + `sendKeys(Key.SPACE)` on an element that is not a text input. This works if you use `sendKeys(' ')` instead, or the Actions API.

Refs:
https://github.com/mozilla/geckodriver/issues/777 
https://github.com/mozilla/geckodriver/issues/846
https://bugzilla.mozilla.org/show_bug.cgi?id=1068733

I'm going to close this since there are multiple workarounds, though anyone can reopen if they feel there's more discussion needed.

**Comment by jongund** [comment]
@smhigley 

Sara thank you for figuring it out!

Jon
