### ISSUE TITLE
Question: Are there plans to release a component library for aria?

### ISSUE THREAD

**Issue by JoshWhite** [w3c/aria-practices#1397]
Hey,

I'm not sure if this is the right forum for my question, but...

Our team is looking to implement wai-aria across a suite of applications, to help them meet [WCAG 2.1](https://www.w3.org/TR/WCAG21/). In our case, this is a vast project and will take considerable investment. 

Some of the examples you provide in the documentation appear to be very well written, cross browser compliant and very reusable ([eg](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/js/Menubutton.js)).

**Are there any plans to release these as a coherent NPM library?**

I think it would be incredibly useful to have a library maintained in line with the documentation.

**Comment by mcking65** [comment]
@JoshWhite, sorry to disappoint, but building a reusable component library goes way beyond the scope of the APG task force. That is a huge undertaking that is not directly related to our mission of helping the web engineering and accessibility communities understand how to utilize ARIA in practice.

WRT component libraries specifically, the role of the APG is to help people who are building them understand what they need to do in order to implement ARIA in a manner that is aligned with the intent of the ARIA specification and related accessibility APIs.

If you have any follow-up questions, please feel free to re-open this issue.

**Comment by carmacleod** [comment]
@JoshWhite
FYI, in case it's helpful... the [Carbon component library](https://www.carbondesignsystem.com/) developers look at the examples in the APG to help develop accessible Carbon components.

**Comment by JoshWhite** [comment]
@carmacleod - thanks for the link. Looks like a really interesting project, but I fear the theme options won't be flexible enough in our case. 

We have an existing brand and component suite across a few technologies. I'm hoping to find / build something which can add WCAG accessibility standards with as little change as possible. 

Its challenging!
