### ISSUE TITLE
Page up/down on day and month for spin button is underspecified and has bug

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1426]
To reproduce:
- Go to the [date picker spin button example](https://w3c.github.io/aria-practices/examples/spinbutton/datepicker-spinbuttons.html)
- Focus on the day spinner
- Change the spinner to have the value of the last day of the month
- Press "page up"
- BUG: Notice that the day becomes the first of the month, not the 4th day of the month

If you change the date spinner to be the first of the month, and send "page down", you get a value that is 4 days before the end of the month. So you can see, page up and page down act differently at the boundaries, and the correct behavior is not explained in the Keyboard Support table.

I think we should always see a 5 unit increase and decrease, rather than turning it into the first or last day available!

Page up and page down for month has the same buggy behavior.

**Comment by nschonni** [comment]
Was playing around with the tests today to see if I could fix it. One thing I was trying was to use END/HOME at the start of the test to get consistent results, but then I ran into the PAGEUP/PAGEDOWN issue where wrapping around the year seems off. EX:
- December + PAGEDOWN = July
- July + PAGEDOWN = February
- February + PAGEDOWN = December

Not sure if the expected behaviour is to still go -5 over the date boundry or if the current "Max Month" is correct
