### ISSUE TITLE
Recommendation for a new aria attribute - "aria-link-list-hide"

### ISSUE THREAD

**Issue by Stefany93** [w3c/aria-practices#1453]
A lot of developers receive accessibility audits where duplicate links are flagged. Duplicate links usually occur in design patterns such as cards, blog post excerpts and product overviews. Having multiple links leading to the same destination is essential for these patterns in order to provide better user experience for sighted mouse and touch users. 

Developers trying to solve the issue often resort to anti-patterns such as this:

`<a href="example.com" role="presentation" aria-hidden="true">Read More</a>`

or this:

`<a href="example.com" tabindex="-1" aria-hidden="true">Read More</a>`

[Big no-no. ](https://www.w3.org/TR/using-aria/#4thrule)

I suggest we introduce a new `aria` attribute which would prevent the cluttering of duplicate links in screen readers' element lists' so it would at least solve the problem half way. The attribute would work like this:

**`<a href="example.com" aria-link-list-hide="true">Read More</a>`**

This way the element would be focusable, but it won't appear in the element lists of screen readers.

**Comment by sinabahram** [comment]
Let's put aside the problematic nature of "read more" in the first place.

Doing so, what is wrong with:
<a href="example.com" tabindex="-1">Read More</a>

If and only if there is another focusable link? This allows virtual cursor-based SR agents to activate the link, doesn't prevent mouse users from doing anything, and doesn't cause extra tab stops for focus-based traversal.

Also, it is usually possible to avoid using duplicate links through other techniques, no? For example, images are usually the problematic element there, but could be given click semantics without keyboard semantics; however, their focus-highlight of course set when the parent link is focussed, and similar strategies. The above isn't meant to be comprehensive, but simply to address the raised concerns.

**Comment by StommePoes** [comment]
I would worry about something trying to tell the difference between a screen reader and some other assistive technology. The idea behind ARIA is generally AT agnostic.

Some people set `aria-hidden="true"` + tabindex="-1" on redundant read more links, and while this appears to solve the issue (it's even mentioned as the better setup in the W3C page linked), it means screen reader users who are low vision (and use the screen reader to assist with reading visible text) can't read out what the link is, while speech rec users can't call the link to click it.

Often these are styled like obvious calls to action or links, while the original redundant link, such as in the heading of a card, only show their heading styles. They're clickable and have good link text, but they don't look like links. The Read More becomes the thing visually telling people where to click to get more content.

This attribute might specifically mess with screen magnification users. The more complex screen mag software offers finding things by type (similar to a screen reader's list of links), but these are sighted users, and they should be able to expect to find things they can see. A browser cannot tell whether it was a screen reader or a screen magnifier who was asking for the list of links, because that action isn't done by the browser.

(I like my screen mag, these are my thoughts)

**Comment by mcking65** [comment]
@Stefany93

Thank you for the feedback.

>Having multiple links leading to the same destination is essential for these patterns in order to provide better user experience for sighted mouse and touch users.

As @sinabahram pointed out, this is not necessarily so. Sighted mouse and touch users need multiple click areas, or click areas larger than the link text. However, nnot all the clickable space has to be contained within the link element. There are multiple ways to engineer this.

@StommePoes points out that ARIA is designed to be assistive technology agnostic, so a feature like this that is designed to manipulate the behavior of a specific feature of a specific type of assistive technology would need a very compelling use case to support it.

If you would like to pursue this further, please raise it as an issue in the [repository for the ARIA specification](https://github.com/w3c/aria). If you think there is something we should do in the authoring practices, please raise an issue with that suggestion.

Closing as "not-for-practices" because this is a request for an ARIA feature.
