### ISSUE TITLE
Update Branch Policies for default branch

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#1548]
On the https://github.com/w3c/aria-practices/settings/branches I think the Travis Required check and add the new "lint" one that seems to be covering all the new jobs.
@mcking65 I could potentially rename the cspell key so you could keep that one as optional.

Think this will block https://github.com/w3c/aria-practices/pull/1523 unless you want me to leave the Travis file with a no-op job till this is updated.

/cc @michael-n-cooper

**Comment by nschonni** [comment]
https://github.com/w3c/aria-practices/pull/1549 should help picking the job names in the UI

**Comment by michael-n-cooper** [comment]
@nschonni Matt asked me to look into this, but I can't tell from the issue description what exactly you need done. Can you provide more context?

**Comment by nschonni** [comment]
I think the minimal "fix" is to go onto https://github.com/w3c/aria-practices/settings/branches and edit the branch policy for master and uncheck Travis as a required check.
I'm not sure if the Actions equivalents actually need to be marked as required, but that would be something for the working group to decide. That could be done separately though

If you do the first part an mark Travis as no longer a required check, then https://github.com/w3c/aria-practices/pull/1576 can land, and you could disable the Travis integration (optional)

**Comment by mcking65** [comment]
@michael-n-cooper 

Unfortunately, this has become urgent.

We aren't using travis for any real checks; it is just a no-op. But, it is [rejecting all our jobs now](https://travis-ci.com/github/w3c/aria-practices/requests) with the message:

>Job rejected
>Owner w3c is not on a new pricing.

This seems to flipped right around 12:30 AM pacific on December 21.

So, we can't merge anything that expects a travis check because travis never returns an answer even for our no op job.

**Comment by mcking65** [comment]
Closing as complete.

We have decided to leave the checks run by the github workflows as optional instead of required for merge. @a11ydoer  and I will only merge if all checks pass unless we are absolutely positive a failure is not due to a problem with the changes in the PR. We want to keep the flexibility of being able to merge in such situations, e.g., some kind of infra problem.

**Comment by nschonni** [comment]
Administrators can always merge things with an override if there is a failing required check. That still adds and extra checkbox of "I really want to override the failing job" rather than an accidental merge with a failure.
