### ISSUE TITLE
meta: Cleaning up old branches

### ISSUE THREAD

**Issue by nschonni** [w3c/aria-practices#1552]
Here are some that I noticed looking at https://github.com/w3c/aria-practices/branches/all
- the ones starting with "greenkeeper" can be removed now that the Dependabot move happened
- branches that indicate they are for merged and/or closed PRs
- branches that have "0" commits ahead of master. The

**Comment by nschonni** [comment]
@mcking65 not sure if you're the best one to tackle this or if @jesdaigle / @zcorpan could do it (if you agree with the cleanup)

**Comment by zcorpan** [comment]
@nschonni yeah this seems like something we could do. Added to the backlog: https://github.com/w3c/aria-practices/projects/29

**Comment by zcorpan** [comment]
Removed:

- `master` (we switched to `main`, but `master` reappeared for some reason)
- `feature/name-change` #1004  Merged
- `car/issue1025` #1029  Closed
- `issue1072-datepicker-dialog-aria-selected-patch` #1073  Closed
- `add-aria-current-to-carousel-example` #1094  Closed
- `zcorpan/demonstrate-build-lint-failure` #1366  Closed
- `zcorpan/ensure-generated-examples-index` #1365  Closed
- `zcorpan/combobox-backspace-tests` #1363  Closed
- `add-jump-to` #1860  Closed
- `jnurthen/issue1900` #1901  Merged
- `slider-valuetext` #1857  Closed
- `fix-bug-index-generator` #1709  Closed
- `issue1800` #1803  Merged
- `update-multithumb-slider` #1704  Closed
- `toolbar-key-tests` #1691  Merged
- `skip-to-example` #1635  Closed
- `index-with-hc` #1607  Closed
- `dependabot/npm_and_yarn/lint-staged-10.5.3` #1658  Merged
- `car/fix-mismatch` #1605  Closed
- `error-on-no-undef` #1429  Closed
- `add-caption-to-table` #1484  Closed
- `utils-file-input-fix` #1470  Merged
- `respec_marcos` #1410  Merged
- `update-carousel-guidance` #1372  Closed
- all `greenkeeper/*`

I haven't removed branches that have no PRs or that are 0 commits ahead of `main`. We could probably delete more here, but I don't know if any given branch is one that should be preserved for some reason.

I would suggest ticking the checkbox "Automatically delete head branches" in GitHub settings for this repo, so that branches are removed automatically after PRs are merged.

https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by zcorpan** [comment]
To remove branches locally in your clone that have been removed upstream, run:

```
git fetch --prune
```

**Comment by zcorpan** [comment]
Thank you, @michael-n-cooper!

I've removed the following branches for closed/merged PRs:

* `zcorpan/widget-states-2` https://github.com/w3c/aria-practices/pull/1277
* `respec-config1.2` https://github.com/w3c/aria-practices/pull/1114
* `issue1102-open-example-jsfiddle` https://github.com/w3c/aria-practices/pull/1111
* `issue1076` https://github.com/w3c/aria-practices/pull/1112
* `issue1106` https://github.com/w3c/aria-practices/pull/1113
* `issue259-aria-level-guidance-slf` https://github.com/w3c/aria-practices/pull/1177
* `windows-ava-fix` https://github.com/w3c/aria-practices/pull/1285
* `BuildFix` https://github.com/w3c/aria-practices/pull/1374
* `tabbed-carousel-opt2` https://github.com/w3c/aria-practices/pull/1377
* `apg-1.2-merge-latest` https://github.com/w3c/aria-practices/pull/1519
* `issue1102-open-example-codepen` https://github.com/w3c/aria-practices/pull/1110
* `codepen-images` https://github.com/w3c/aria-practices/pull/1534
* `fix-carousel-link` https://github.com/w3c/aria-practices/pull/1530
* `issue1467` https://github.com/w3c/aria-practices/pull/1468
* `update-apg-1.2` https://github.com/w3c/aria-practices/pull/1583
* `979-meter-pattern` https://github.com/w3c/aria-practices/pull/1189
* `issue1748` https://github.com/w3c/aria-practices/pull/1749
* `add-role-none` https://github.com/w3c/aria-practices/pull/1806
* `slider-thermostat-update` https://github.com/w3c/aria-practices/pull/1755
* `accordion-checkbox` https://github.com/w3c/aria-practices/pull/1833
* `menu-button-scroll-to` https://github.com/w3c/aria-practices/pull/2057
* `update-checkbox` https://github.com/w3c/aria-practices/pull/1802

There are still a few pages of [stale branches](https://github.com/w3c/aria-practices/branches/stale), without PRs or with open PRs, which I haven't removed. Again, not sure how to evaluate what to remove from these.

I'll say that this issue is fixed now.

**Comment by nschonni** [comment]
Thanks! I think there are a few more of the "0 ahead commits" branches likes that can be cleaned too
![image](https://user-images.githubusercontent.com/1297909/139510669-4ba7cea4-737a-40a9-bbc8-8786d8f39fae.png)

**Comment by nschonni** [comment]
Few last Greenkeeper ones too 
![image](https://user-images.githubusercontent.com/1297909/139510712-851f8fae-c60f-4a00-9802-bdefb30f387a.png)

**Comment by zcorpan** [comment]
0 ahead commits branches removed:

* `1399`
* `thermo`
* `skipto`
* `update-datepicker-javascript-code`
* `1007`
* `1037`
* `tool`
* `datepicker`
* `wiki`

Greekeeper:

* `greenkeeper/lint-staged-10.1.5`

**Comment by nschonni** [comment]
Awesome! The rest of the non-PR'd stale branches would need some sort of review by the authors to see if there is anything useful, so I think this can remain close, unless you want to give homework at your next meeting 😆
