### ISSUE TITLE
Review data grid examples

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#160]
The data grid examples developed for issue #104 are ready for review. The example page is at:http://w3c.github.io/aria-practices/examples/grid/dataGrids.html

#### Requested Reviews

- [x] Review by @annabbott 
- [x] Review by @accdc 
- [x] Review by @jnurthen

**Comment by accdc** [comment]
Hi Matt, been testing the examples, and some of the grid functionality doesn't always match the instructions at the bottom of each grid, specifically which columns are sortable like Description which is actually static, also which column cells are editable such as Amount.

Another question about aria-rowindex, I thought this was to be used on role=row, <tr> and not role=gridcell <td>, because a rowindex is relative to the row, not the horizontal cell, and what if focus is on the TR instead of the TD, such as when arrowing up and down between selectable grid roles?

**Comment by accdc** [comment]
Looks like GitHub messed up my markup.

Basically I was referring to the scenario when TR rows have focus and the up / down arrow keys are used to move between them, where aria-rowindex is valid. I was unaware that aria-rowindex is valid on TD, because it seems like a lot of duplication, why not just set this once on TR?

**Comment by mcking65** [comment]
@accdc, thank you, thank you. Some excellent catches!

You are right, my notes below the example are out of sync with the example. I'll fix ASAP ... Thanks Giving vacation is about to begin for me so not sure if I will sneak it in before next week.

Also, on rowindex, it is valid on cells, but when on cells, it should also be on the row. We will fix that.  For the purpose of demonstrating assistive technology support, we may want to have it on the rows and not the cells in one example and on both rows and cells in another.

**Comment by jongund** [comment]
Visual styling of what cell the keyboard focus is on also should be improved.   Currently seems to rely on the default browser focus and is difficult to see.

**Comment by annabbott** [comment]
Reviewed Data Grid Examples (http://w3c.github.io/aria-practices/examples/grid/dataGrids.html):

First paragraph:
"Following are three example implementations of the design pattern for grid that demonstrate the keyboard interactions and ARIA features that enable accessible presentation of tabular information. "

Suggested edit:
""Following are three example implementations of the design pattern for grid that demonstrate the keyboard interactions and ARIA features that enable accessible presentation of tabular information, some of which is interactive. "

Without specifying "interactive", there's no difference between a grid and a data table.

**Comment by annabbott** [comment]
Continuation of Reviewed Data Grid Examples (http://w3c.github.io/aria-practices/examples/grid/dataGrids.html):

Example 1 > Notes:
"4. header cells are not focusable since they do not provide any functionality, they can be announced by screen readers as labels, and are also navigable with the reading mode of screen readers. "

Edits needed: 
- capitalize "H" in "Header"
- Split into two sentences: Add period after "functionality" and capitalize "T" in "They"

**Comment by annabbott** [comment]
Continuation of Reviewed Data Grid Examples (http://w3c.github.io/aria-practices/examples/grid/dataGrids.html):

Example 2 > Notes:
"1. The navigation keys and functions are the same as example 1 except that the column headers are now focusable."

Edit needed: 
"1. The navigation keys and functions are the same as example 1 except that the first column header for Date is now focusable because it provides function (sort)."

Oddity: once sorted on Date, the sort cannot be reversed. Generally these sorts toggle...

Based on the edit above, remove 2. as it is only partially true: Description column is not sortable.

Likewise remove 4 as amounts cannot be edited in this example.

**Comment by MichielBijl** [comment]
Question: should the first column (the dates) be table headers?

**Comment by mcking65** [comment]
@MichielBijl, usually when reading this kind of information, I would want the description as a row header, and sometimes the date.  There is no clear choice for a row header. 

In situations like this, screen reader functions that allow the user to designate which columns to treat as row headers can be very useful.

In advanced applications, the application itself could provide this kind of functionality. For example, it could treat the first column as the header and let the user choose which column is at the left. This is almost essential functionality for apps like an inbox. It is also beyond the scope of this example. Perhaps we could make such examples for release 2.

For this case, I am leaning toward not providing a row header just to demonstrate that it is not always needed.

**Comment by annabbott** [comment]
In Example 2: Sortable Data Grid With Editable Cells, there is no visual indication that the Amount column is sortable. The visual indicator for sort should be persistent on all headers where the column is sortable and not displayed solely dependent on focus.

**Comment by annabbott** [comment]
The first bullet for aria-rowcount="16" states:
In example 3, specified because a total of 16 rows are available, but fewer than 16 rows are visible to assistive technologies.
Suggested edit because no user has visibility to more rows:
In example 3, specified because a total of 16 rows are available, but fewer than 16 rows are visible.

**Comment by annabbott** [comment]
The first bullet for aria-colcount="6" states:
In example 3, specified because a total of 6 columns are available, but when columns are hidden, fewer than 6 columns are visible to assistive technologies.
Suggested edit because no user has visibility to more columns:
In example 3, specified because a total of 6 columns are available, but when columns are hidden, fewer than 6 columns are visible.

**Comment by mcking65** [comment]
Thank you all for the excellent feedback; it has all been addressed. Closing!
