### ISSUE TITLE
Button IDL styling does not work on all browsers

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#1692]
The Button IDL styling ([css/button.css](https://github.com/w3c/aria-practices/blob/master/examples/button/css/button.css)) is not applied for:
- Firefox, linux
- Chrome, linux
- Edge, Windows
- Firefox, Windows

Where as it does appear to work in Chrome on Windows. See some discussion in #1681

**Comment by carmacleod** [comment]
Works ok in Safari on macOS.

**Comment by carmacleod** [comment]
@spectranaut 

Oh. _Duh_. 😧 
I figured out what's going on here.
It doesn't work in all browsers because the IDL feature being shown (attribute reflection) isn't supported in all browsers yet.
You would think I would have remembered this... https://github.com/w3c/aria-practices/pull/1161#issuecomment-527296049 was only a year ago!

To recap, here are those testing notes again, with a couple of 2020 updates:

NOTE: To test, need to do the following:

**Chrome**: Works by default now in Windows Chrome.
(May work in Chrome Canary on Linux/Mac with chrome://flags/#enable-experimental-web-platform-features enabled.)

**Edge**: Use Edge Beta, Dev or Canary and enable edge://flags/#enable-experimental-web-platform-features

**Firefox**: Not supported yet, not even in beta with accessibility.AOM.enabled=true on the about:config page
(The [Mozilla issue for AOM](https://bugzilla.mozilla.org/show_bug.cgi?id=1313691) hasn't been updated in 2 years).

**Safari**: Reflection works in Safari. Didn't need to enable anything.

**Comment by carmacleod** [comment]
Leaving this issue open to revisit the tiny little warning on the IDL example page - it's clearly not visible enough!
Currently it just says:
> IMPORTANT: This example uses features of the draft ARIA 1.2 specification. As a draft specification, it is subject to change. Support provided by browsers or assistive technologies is experimental.

Maybe we should use the red-colored Warning box, or the "advisement" class to make it stand out more.
Maybe we should also point to this issue, or write the current testing instructions in the warning box, or something.
