### ISSUE TITLE
Review File Directory Treeview Example Using Computed Properties

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#223]
This issue is for collecting feedback on and tracking editorial revisions to the 
[File Directory Treeview Example Using Computed Properties](http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html).

#### Required updates

- [x] Fix tab trap issue reported by @stevelove 
- [x] Issue #367: File Directory Tree View examples: modifier keys are not correctly handled 
- [x] Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by stevelove** [comment]
The tab key is getting trapped in Firefox and I am unable to navigate away from the File Directory Treeview via the keyboard. I was not able to reproduce the issue in the other browsers I tested (Chrome and Edge).

**Browser**: Firefox 50.1.0 and Firefox 51 beta
**Operating System**: Centos 7.5

**Steps to reproduce:**
1. Visit https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-1/treeview-1a.html in the latest Firefox.
2. Press tab until the Treeview has focus.
3. Press tab again.
4. Observe that tab focus is trapped on the Treeview.

**Details**
The problem seems to be in `Treeitem.prototype.handleKeypress`, which is triggered by pressing Tab in Firefox. In this case, the KeyboardEvent gives us `charCode: 0` and `keyCode: 9`. 

As a result:
`var char = String.fromCharCode(event.charCode); // ""`
`isPrintableCharacter(char) // [""]`

The code goes into the printable character condition and `event.stopPropagation()` and `event.preventDefault()` are both called, trapping the Tab key.

Since pressing a printable key reverses the usable properties in the event, i.e. "s" results in `charCode: 115` and `keyCode: 0`, I found that doing something along the lines of `String.fromCharCode(event.charCode || event.keyCode)` fixes the problem, though there may be a better solution.

**Comment by mcking65** [comment]
@stevelove 

Thank you for the feedback! I can reproduce the bug.

**Comment by annabbott** [comment]
In the Keyboard Support section, currently the following is listed:
Home 	Moves focus to first node.
End 	Moves focus to the last node that can be focused without expanding any nodes that are closed.

Question: does Home expand any nodes that are closed?

Also, in the functional example, there seems to be some residual grey background when focus and selection are moved using FF.

**Comment by mcking65** [comment]
Two more issues that need to be resolved before we can complete this review:

1. Issue #367: File Directory Tree View examples: modifier keys are not correctly handled 
2. Issue #365: Tree View Examples: Fix Incorrect Left Arrow Behavior

**Comment by mcking65** [comment]
This issue is now dependent on issues #365, #385, and #386.

**Comment by mcking65** [comment]
The following paragraph in the accessibility features section does not explain the accessibility benefit or purpose of the feature:

> The expandable nodes (parent items) in the tree have a custom focus and hover styling created using CSS focus and hover classes. To do this, focus, blur, mouseover, and mouseout events trigger application of classes to the span element that contains the visible label of the treeitem. 

How is the treeview more accessible with the custom focus and hover?

**Comment by annabbott** [comment]
Verified edit to Keyboard Support section > Home Key description.

**Comment by MichielBijl** [comment]
Why are the hover and focus states implemented via JavaScript rather than `:hover` and `:focus`?

**Comment by mcking65** [comment]
All feedback has been addressed except for how the focus indicator is customized, which is being tracked by issue 404. Closing this issue to complete the task force review process.
