### ISSUE TITLE
Home page: multiple header elements 

### ISSUE THREAD

**Issue by shirsha** [w3c/aria-practices#2350]
- On the home page there are several issues with the landmarks:
   -  All content is not placed inside the landmark. For example, the banner content is not placed inside an header element.
   - An header element is used inside the aside landmark which contains the heading " Help improve this page.
   - The main content is placed inside the header element.
   - There is an empty footer element on the page.

**Comment by mcking65** [comment]
@shirsha 
The only feedback I understand in this issue is the missing banner landmark, which is dependent on w3c/wai-minimal-header-design#96.

I opened a separate wai/apg site issue to track the banner issue and dependency on the templat: w3c/wai-aria-practices#106.

I don't know what to do about the other feedback you are providing in this issue because there is not enough information to identify a problem. Will you please raise separate issues for each, and please provide code snippets or more detail so we can understand what the problem is?

**Comment by shirsha** [comment]
@mcking65 
My statements got messed up as I was using chevrons for header and footer elements. 
I have removed them from my initial comments.
Sorry for the confusion


Thanks,
Siri

**Comment by isaacdurazo** [comment]
This seems to be solved. @shirsha please feel free to re-open if I'm mistaken
