### ISSUE TITLE
Combobox pattern is too versatile

### ISSUE THREAD

**Issue by JAWS-test** [w3c/aria-practices#2504]
[APG says about combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/):

>  An editable combobox may either allow users to input any arbitrary value, or it may restrict its value to a discrete set of allowed values, in which case typing input serves to filter suggestions presented in the popup

How should I know with and without AT if I am allowed to enter free text or have to enter or select a predefined value. I give to consider that in HTML there is a clear distinction between the select element and the input element with list attribute:
* select = drop-down list. A value must be selected
* input list = combined input field. Any value can be entered.

HTML does not know a combobox without free value input. Therefore I wonder with which method this information should be transmitted that text input for filtering is possible, but not free text input.

Furthermore, I wonder if  role=combobox is allowed if the popup cannot be shown without text input and in my opinion it is not a combined input field at all, but an input field with autocomplete. Whether combobox should also be allowed in these cases: how is perceptible with AT that I have to enter text before I can open the popup or it opens automatically?

Also, I wonder if it is not relevant to know what content the popup offers:
* all valid values
* some valid value, filtered according to my input.
* any values, suggested based on my input
* any values, unrelated to my input

All variants seem to be allowed (even if the HTML combined input field supports only one of the 4). For sighted people it is quickly obvious which values are offered in the popup. For AT users not. Wouldn't it be important for them to be able to perceive this efficiently, so they don't have to read all the entries individually first?

Here I see 2 possibilities:
* new ARIA attribute to convey this information or
* prohibition of the 3 variants which are not compliant with the HTML standard

**Comment by mcking65** [comment]
There are tradeoffs between Versatility and rigidity. Thus, with versatility, there are potential problems, including the ones you raise.

Important questions:
* Are the problems real? Do we have evidence  of negative impacts?
* If the problems are real, are there solutions that do not require reducing the versatility of the pattern?
* If the problems are real, is the best way to solve them with ARIA attributes? Or, should they be solved by product designers, e.g., better instructions and error messages?

Regardless, the definition of combobox is the domain of the ARIA specification, not the APG. So, I am closing this issue as not-for-practices. However, if   my responses below, are not sufficient and you would like further discussion, please raise an ARIA issue.

@JAWS-test wrote:

> How should I know with and without AT if I am allowed to enter free text or have to enter or select a predefined value.

Generally, this is the responsibility of the UI design, both content and visual presentation.

> HTML does not know a combobox without free value input. Therefore I wonder with which method this information should be transmitted that text input for filtering is possible, but not free text input.

One purpose of ARIA is to facilitate accessibility for the types of widgets that authors create with JS because they cannot create them with only HTML and CSS. So, you will not find an answer to questions such as this in HTML (as it exists today).

> Furthermore, I wonder if role=combobox is allowed if the popup cannot be shown without text input and in my opinion it is not a combined input field at all, but an input field with autocomplete. Whether combobox should also be allowed in these cases: how is perceptible with AT that I have to enter text before I can open the popup or it opens automatically?

Whether or how   a UI makes its interaction model perceivable is a design decision that authors need to make. ARIA is just one means of communicating information about interaction, and it is not the only one. In other words, ARIA is not intended to be a comprehensive interaction descriptor.

If we overload ARIA with too much meaning, it could have a negative impact on usability. This is why it is important that ARIA prioritize solving problems where there is both evidence of real-world impact and it is clear that a programatic solution is superior to alternatives.

> Also, I wonder if it is not relevant to know what content the popup offers:
> 
> * all valid values
> * some valid value, filtered according to my input.
> * any values, suggested based on my input
> * any values, unrelated to my input
>
>For sighted people it is quickly obvious which values are offered in the popup. For AT users not. Wouldn't it be important for them to be able to perceive this efficiently, so they don't have to read all the entries individually first?

It is possible that reading entries in the list is the most efficient and best way. That is how non-AT users gain the same understanding.

My personal experience as someone who is blind is not a proxy for data, but I will nonetheless offer it  as one lens for looking at the question you raise. For me, scanning  the list is efficient. I have control over it. I can do it at any speed I wish. If I had to wait around for some automatic announcement, it is likely   I might not  hear it because there is already so much information that is announced automatically.

Users  also gain significant benefit from scanning the content of a suggestion list because it helps them  better understand the UI. I think there may even be a reasonable assumption on the part of designers that most  users will  be aware of the actual content of a suggestion list.
There are tradeoffs between Versatility and rigidity. Thus, with versatility, there are potential problems, including the ones you raise.

Important questions:
* Are the problems real? Do we have evidence  of negative impacts?
* If the problems are real, are there solutions that do not require reducing the versatility of the pattern?
* If the problems are real, is the best way to solve them with ARIA attributes? Or, should they be solved by product designers, e.g., better instructions and error messages?

Regardless, the definition of combobox is the domain of the ARIA specification, not the APG. So, I am closing this issue as not-for-practices. However, if   my responses below, are not sufficient and you would like further discussion, please raise an ARIA issue.

> How should I know with and without AT if I am allowed to enter free text or have to enter or select a predefined value.

Generally, this is the responsibility of the UI design, both content and visual presentation.

> HTML does not know a combobox without free value input. Therefore I wonder with which method this information should be transmitted that text input for filtering is possible, but not free text input.

One purpose of ARIA is to facilitate accessibility for the types of widgets that authors create with JS because they cannot create them with only HTML and CSS. So, you will not find an answer to questions such as this in HTML (as it exists today).

> Furthermore, I wonder if role=combobox is allowed if the popup cannot be shown without text input and in my opinion it is not a combined input field at all, but an input field with autocomplete. Whether combobox should also be allowed in these cases: how is perceptible with AT that I have to enter text before I can open the popup or it opens automatically?

Whether or how   a UI makes its interaction model perceivable is a design decision that authors need to make. ARIA is just one means of communicating information about interaction, and it is not the only one. In other words, ARIA is not intended to be a comprehensive interaction descriptor.

If we overload ARIA with too much meaning, it could have a negative impact on usability. This is why it is important that ARIA prioritize solving problems where there is both evidence of real-world impact and it is clear that a programatic solution is superior to alternatives.

> Also, I wonder if it is not relevant to know what content the popup offers:
> 
> * all valid values
> * some valid value, filtered according to my input.
> * any values, suggested based on my input
> * any values, unrelated to my input
>
>For sighted people it is quickly obvious which values are offered in the popup. For AT users not. Wouldn't it be important for them to be able to perceive this efficiently, so they don't have to read all the entries individually first?

It is possible that reading entries in the list is the most efficient and best way. That is how non-AT users gain the same understanding.

My personal experience as someone who is blind is not a proxy for data, but I will nonetheless offer it  as one lens for looking at the question you raise. For me, scanning  the list is efficient. I have control over it. I can do it at any speed I wish. If I had to wait around for some automatic announcement, it is likely   I might not  hear it because there is already so much information that is announced automatically.

Users  also gain significant benefit from scanning the content of a suggestion list because it helps them  better understand the UI. I think there may even be a reasonable assumption on the part of designers that most  users will  be aware of the actual content of a suggestion list.

**Comment by JAWS-test** [comment]
@mcking65 Thank you very much for your detailed answer. I opened the ticket here and not at ARIA because the ARIA specification explicitly refers to APG:

> See the [WAI-ARIA Authoring Practices](https://w3c.github.io/aria-practices/) for additional details on implementing combobox design patterns.

The rules regarding combobox that I am concerned about are in the APG rather than directly in the ARIA specification.

I am aware that ARIA aims to enable things that HTML cannot. But I see the problem with combobox in the ambiguity. In HTML there are no tabs, with ARIA I can use role=tablist, tab and tabpanel and get tabs whose markup and operation is very clear. Unfortunately, this is not true for the combined input fields.

You wrote:

> Generally, this is the responsibility of the UI design, both content and visual presentation.

But I thought it is exactly the aim of APG to propose good patterns here, maybe visually, but above all also programmatically. What would a good pattern look like, which communicates whether free text input is possible or not? In practice, I often see only bad patterns: e.g. after leaving the field or after saving the form, the value in the combined input field is simply deleted because it does not correspond to any value from the list. This is especially imperceptible with AT and thus a big problem. I have been testing web applications for accessibility for many years and encounter this problem very often. 

What would a good pattern look like, which conveys that text has to be entered first, so that the popup can be opened. Should such a field have an input hint: "Enter at least 2 characters to use the value help"?

**Comment by JAWS-test** [comment]
In addition, there are the following aspects:
* AT sometimes outputs input hints, e.g. JAWS: "Enter text or navigate with the arrow keys" - but both are not possible with some patterns. Maybe this is just a bug of JAWS, but what input hint should JAWS give when combobox is so versatile?
* If there is a role=combobox at an HTML-input, then this input can automatically show autocomplete values of the browser - in addition to the list entries of the application. With the screen reader I can't perceive the difference. I have to close the browser's autocomplete list with ESC first to be able to use the application's list. But if I can't tell with screen reader that it's not the application's list at all, I won't close it with ESC. This is more of a browser problem, but should be considered in this context.
