### ISSUE TITLE
role="button" is still required in case of role="columnheader" is used?

### ISSUE THREAD

**Issue by AccessibilityEnthusiastic** [w3c/aria-practices#2531]
Hi Team,

I would like to know if role="columnheader" is used along with aria-sort. Do we still need to use/required the role="button" here
![Sorting](https://user-images.githubusercontent.com/115781693/199216825-d5a0bcc0-9e6b-4df9-9903-239c159d24d7.png)

**Comment by JAWS-test** [comment]
The [APG example](https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html) use the button inside the columnheader.

This is necessary because columnheader or gridcell are not controls, but containers for content or controls. Therefore all controls inside columnheader or gridcell must have a correct role, so that it is clear that
* they can be operated
* how they can be operated
