### ISSUE TITLE
Ambiguities in the button example

### ISSUE THREAD

**Issue by Andreas-Englisch** [w3c/aria-practices#2559]
https://www.w3.org/WAI/ARIA/apg/example-index/button/button_idl.html

Table "Role, Property, State, and Tabindex Attributes", column "Element":
* row 1+2: "div, a"
* row 3+4: only "a" - why not div or button? (button would be much better than div or a for a toggle button, especially when using the Windows High Contrast Mode) 

column "Usage", row 1: "Set in javascript with element.role = 'button';" - This is not wrong. But wouldn't it be easier not to use JS here to assign a role afterwards, but to use role=button right in the source code

**Comment by giacomo-petri** [comment]
Andreas,

I assume that the table is referring to the specific 2 examples above.

So:
* the first example consists in a div element styled as a button and semantically managed as a button;
* the second example instead consists in an <a> tag managed as a toggle button; that's why the aria-pressed is specific for the a element, which refer only to the specific scenario. Of course you can set this semantics to other elements (div, span, button, etc.).
