### ISSUE TITLE
Question: Accordion Implementation vs using <details> > <summary>

### ISSUE THREAD

**Issue by StfBauer** [w3c/aria-practices#2565]
One question on the accordion implementation.
https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html

I totally understand the implementation but why doesn't it use `<details>` `<summary>`

Would not this accomplish the same accordion just without any javascript involved and would just work with HTML only.

I wonder what the downsides are and is the shown implementation just in a way to work with old browser?

Thank you in advance.

**Comment by JAWS-test** [comment]
Many patterns shown here will work without ARIA. And they should be implemented in a perfect world without ARIA (https://www.w3.org/TR/using-aria/#rule1). Unfortunately, we don't live in a perfect world and many web developers don't like HTML or don't like the visual limitations of HTML (some elements can't be fully styled with CSS). That's why the patterns show ways to implement things with ARIA, but which are usually better implemented with HTML. It would make sense to mark with each example whether the respective pattern also works with HTML or not. To my knowledge, this has also been discussed here before, but unfortunately not yet implemented. But we already have the warning at the top of the page:

> Robust accessibility can be further optimized by choosing implementation patterns that [maximize use of semantic HTML](https://www.w3.org/TR/using-aria/#rule1) and heeding the warning that [No ARIA is better than Bad ARIA](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/#no_aria_better_bad_aria).

**Comment by StfBauer** [comment]
Thank you @JAWS-test - I have assumed so.

**Comment by mcking65** [comment]
It is easy to make a [disclosure](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/) with details/summary. The primary difference between the accordion and disclosure patterns is the accordion pattern includes headings. It is not possible to implement headings with details/summary.

If this, in combination with the information from JAWS-Test  does not answer your question fully, please feel free to re-open the issue.

**Comment by StfBauer** [comment]
Thanx @mcking65 

> The accordion pattern includes headings.

One last question. can't I include headings in the summary?

**Comment by JAWS-test** [comment]
> can't I include headings in the summary?

According to the [HTML specification](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element), just about anything can be in a summary: Headings, links, videos etc.
But: Many browsers treat the summary element like a button (which makes sense in itself) and a [button](https://www.w3.org/TR/wai-aria-1.2/#button) has implicit [role=presentation for all children](https://www.w3.org/TR/wai-aria-1.2/#childrenArePresentational), which means that all child elements have no role. If a heading or link has no role, its semantics will not be output by the screen reader. In practice, some screen readers output the roles anyway, others do not. Thus, a summary should currently contain only text and nothing else. 

See: https://github.com/w3c/html-aam/issues/345 and https://github.com/FreedomScientific/VFO-standards-support/issues/591
