### ISSUE TITLE
Adopt ECMAScript modules

### ISSUE THREAD

**Issue by a11ydoer** [w3c/aria-practices#2671]
In terms of the code review, i worked with @alflennik to derive the following:
- validated that that the addition of `listitem.scrollIntoView({ block: 'nearest', inline: 'nearest'` is working
- validated that the addition of the eslint-disable-line comments did in fact eliminate the lint error (**although, there are notes on this below**)

It is important to note that even though disabling the error did disable the error, it did not address the error in and of itself, and therefore cannot be a resolution to the issue at hand. 

Thankfully @jugglinmike has created a PR that addresses the eslint errors. It can be found here: https://github.com/w3c/aria-practices/pull/2642 

A more in-depth explanation is provided in the PR itself, but to provide a summary here:
> Because of existing code sharing logic in the project, any iterations away from the existing logic will conflict with the current setup. 

> It makes sense to apply these changes in a PR separate from this one to address this holistically in the project and not just on this pattern in particular. Therefore keeping the logic the same for this patch.

If you are in alignment with the above, we can go ahead and merge it in for you :)

_Originally posted by @aleenaloves in https://github.com/w3c/aria-practices/issues/2622#issuecomment-1462866142_

**Comment by a11ydoer** [comment]
@jugglinmike @jongund By any chance, do we know what is the current status of this work in the updated listbox example? I appreciate any update on eslint errors.

**Comment by jugglinmike** [comment]
As discussed during today's meeting (notes posted above), we're going to use this issue to track the project's adoption of ECMAScript modules.

@mcking65 My GitHub account doesn't have the necessarily privileges to modify issues in this repository. Can you rename this one to, "Adopt ECMAScript modules"?

**Comment by mcking65** [comment]
@jugglinmike 

Could you please outline the steps we need to take to resolve this issue?

**Comment by jugglinmike** [comment]
We discussed this plan a few months ago and agreed that it is no longer a priority. The trouble is that adopting ECMAScript modules would involve adding complexity to the contribution experience (in the form of a build step or a local development server), and the CG does no wish to do that at this time.

Further context: the current contribution experience entails loading source files directly into the browser from the hard drive. In terms of transport, this means using the `file:` protocol. However, [web browsers do not necessarily load ECMAScript modules over the `file:` protocol](https://matrix.to/#/!AGetWbsMpFPdSgUrbs:matrix.org/$usRz9Gm3d0gik886BarUncY67R-sQmcqFsePMPzyQ0I?via=matrix.org&via=mozilla.org&via=igalia.com). In order to maintain code that uses `import` declarations, we would either need to provide a build process which performed the "linking" step statically, or we would need to provide a web server so the files could be loaded over the `http:` protocol, instead.
