### ISSUE TITLE
About Section: Add page about contributing with information on joining the group, group communication, and learning how to contribute

### ISSUE THREAD

**Issue by jongund** [w3c/aria-practices#2706]
I suggest we add information on joining the APG working group and links to our e-mail communication list archive on the "About" page of the APG website.

About Page:
https://www.w3.org/WAI/ARIA/apg/about/

**Comment by daniel-montalvo** [comment]
Hi @jongund 

+1 to that.

APG is a Task Force under the ARIA Working Group. For people to be able to join APG, they should be first participants of the ARIA WG, either through a member organization or because they are W3C Invited Experts.

Contributing without being an ARIA WG participant is still possible, and I think we should add language around that as well.

**Comment by mcking65** [comment]
We have this information on the home page. In addition to the home page content, a separate page that is linked from the about page could be helpful.

I propose the title of the page would be "Contributing to the APG". It could start with the information discussed here, but it could also lead people to a variety of other resources related to learning how to contribute.

**Comment by mcking65** [comment]
I started a draft pr -- #2734. It is just a shell with a cleaned up copy of the content from the home page.

I'll seek volunteers to continue work on it at subsequent meetings, starting this week.

**Comment by mcking65** [comment]
Thank you @jongund, @daniel-montalvo, @a11ydoer, and @andreancardona for helping deliver this.

It will be included in the October 3, 2023 publication.
