### ISSUE TITLE
Consider adding aria-pressed to the aria-sort button

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/aria-practices#2817]
Recent discussions with a screen reader user identified that adding aria-pressed to the button that toggles aria-sort ascending, descending, is a good idea, and can be useful to provide information other than 'Header: cell name > button > Column X'. 

Overall I find aria-sort very buggy in both JAWS and NVDA. Sometimes nothing is announced running NVD toggling aria-sort, and JAWS seems to move focus unexpectedly when navigating to sortable column header cells using Ctrl + Alt +Arrow key and then toggling the button.

Tested aria-sort on the APG example, and on a personal project  'REACT Sortable table'

**References**

- [ARIA Authoring Practices Guide (APG)](https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/sortable-table/)
- [MDN Docs aria-sort](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort)
- [REACT Components for personal testing - Sortable Table](https://react-accessible-component-project.netlify.app/?path=/story/tables-table-sort-function--sortable-table-columns)

**Comment by mcking65** [comment]
@LaurenceRLewis 

Could you please explain the problem that you are hoping to solve with this proposal?

With a better understanding of the problem, we could work toward a solution. This specific proposal is not consistent with the toggle button pattern and the intent of aria-pressed.

The implementation of aria-pressed in your react example is not consistent with the definition of a toggle. Activating a toggle should change the value of aria-pressed. In your example, you can press the toggle, but you can't un-press it. In the implementation you proposed, users have to interact with a different element in order to change the state of the toggle to aria-pressed=false.

BTW, consistent screen reader support for accessibility semantics is the objective of the [ARIA-AT project](https://aria-at.w3.org/). ARIA-AT is nearing completion of major updates to the testing infra and capabilities that will enable us to address feedback initiated by the launch of the first version of APG AT Support tables. ARIA-AT should be covering aria-sort in 2024.

**Comment by LaurenceRLewis** [comment]
I have updated the example, thanks for pointing out I had not built the toggle button correctly. Aria-pressed can now be toggled.

This stems from workplace discussions on how to best implement a sortable table. Although the MDN docs are publicly editable, I decided to build the example with an option for aria-pressed. Aria-sort is implemented as recommended in the ARIA spec, and I have included various control options for complete testing.

There is no problem per say, I am seeking an understanding if the aria-pressed does help as documented in the MDN aria-sort, or does it add confusion. Does it make sense for Ascending to be pressed false and Descending pressed true.

My aim is to ensure I contribute in a positive way to accessibility, and that the recommendations I make to the developers in my workplace are founded in meeting the specifications and best practices. The only way I can do this is to ask these questions and build working examples.

**Comment by mcking65** [comment]
@LaurenceRLewis wrote:

> There is no problem per say, I am seeking an understanding if the aria-pressed does help as documented in the MDN aria-sort, or does it add confusion. Does it make sense for Ascending to be pressed false and Descending pressed true.

I don't think it makes sense. The purpose of aria-sort is to communicate whether or not a column is sortable and if it is sorted, how it is sorted. There is no need for an additional attribute to communicate that information. In addition, it is not clear how users or AT could infer that pressed is ascending and not pressed is descending. Not pressed could just as easily be not sorted, as it was in your original implementation.

Net: aria-pressed would add extra markup that adds potential for confusion rather than additional clarity.

> My aim is to ensure I contribute in a positive way to accessibility, and that the recommendations I make to the developers in my workplace are founded in meeting the specifications and best practices. The only way I can do this is to ask questions and build working examples.

Which is **AWESOME**!! Thank you, thank you!!
