### ISSUE TITLE
Include link to GitHub in introduction

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#288]
Status of This Document says:

> If you wish to make comments regarding this document, please send them to public-aria@w3.org (subscribe, archives). All comments are welcome.

Since we’re mostly on GitHub and have all our issues here it might be better to change this line to say 

> please file an issue on GitHub. All comments are welcome.

**Comment by mcking65** [comment]
@michielBijl, we have this in the status of the document section in the publication branch. See:
https://www.w3.org/TR/wai-aria-practices-1.1/

@michael-n-cooper, is there any reason why I shouldn'make the status of this document section the same in master as it was in the Dec 14 heartbeat?

**Comment by mcking65** [comment]
@michael-n-cooper, 

I added an SOD section to the editor's draft.

How do I tell respec not to insert the redundant paragraph that reads:

> This document was published by the Accessible Rich Internet Applications Working Group  as an Editor's Draft. If you wish to make comments regarding this document, please send them to public-aria@w3.org (subscribe, archives). All comments are welcome.

**Comment by MichielBijl** [comment]
There is an [outstanding issue on the ReSpec repo](https://github.com/w3c/respec/issues/919).

**Comment by michael-n-cooper** [comment]
sorry, didn't see this thread before, I haven't figured out how to separate gh emails that are directed at me from the scads of ones that are just sent to me, so I didn't notice the subject line as potentially interesting on this before now.

The editors' draft should not have the same status as the TR publication, as they have different roles.

Normally, the respec boilerplate for editors drafts is sufficient, but you can put in additional content if you want. The comment instructions paragraph is a common one to include. That will create redundant information with the comment instructions respec generates - which includes information that is wrong for us - but normally I live with it for editors' drafts. In the respec issue MB references SM says there is an undocumented feature to suppress that, but because it's undocumented I don't know how to use it so haven't in spite of a great desire to. If you can figure out how it works, great.

**Comment by mcking65** [comment]
OK, thank you @michael-n-cooper, we will tolerate the small amount of redundancy in the status section of the editor's draft. We at least now have the github link in the editor's draft. Closing as complete.
