### ISSUE TITLE
Tabs widget has aria-controls attributes that point to hidden elements

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#293]
You can’t control something that isn’t visible. `aria-controls` should only be added to `role=tab`s that have `aria-selected=true`.

[Related conversation on Twitter](https://twitter.com/LeonieWatson/status/832616204187480065)
[Related issue against the ARIA spec](https://github.com/w3c/aria/issues/531)

**Comment by mcking65** [comment]
@MichielBijl wrote:

> You can’t control something that isn’t visible.  aria-controls  should only be added to  role=tab s that have  aria-selected=true .

Completely disagree! You are controlling the visibility!

This is not a bug. We should not change the examples of tabs because the example conforms with the spec. There are very good reasons for leaving the spec as is. See my comments in issue w3c/aria#531.

This idea does not scale. Imagine applying this rule at scale and across other relationships, e.g., aria-owns,  using the same rationale. This would create perf problems and all kinds of ridiculousness.

As I described in issue 531, there are other ways of addressing the concerns raised by @LJWatson.

Removing the bug label and marking wontfix. If consensus forms in support of such an authoring requirement in ARIA issue 531, we'll reflag it as a bug and put in a milestone that conincides with the ARIA change. We need to keep the authoring practices consistent with the specification unless there is broad consensus that the specification has a critical flaw.

**Comment by MichielBijl** [comment]
> I am removing the bug label and marking this issue invalid. If consensus forms in support of such an authoring requirement in ARIA issue 531, we'll reflag it as a bug and put in a milestone that coincides with the ARIA change.

Sounds good. Am closing this for now.
