### ISSUE TITLE
Incorrect cursor style in Tabs example

### ISSUE THREAD

**Issue by ryo-manba** [w3c/aria-practices#2951]
In the [Example of Tabs with Automatic Activation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/), the tabs are styled with `cursor: pointer`. However, according to the [CSS2 spec](https://www.w3.org/TR/CSS21/ui.html), the pointer cursor indicates a link, but tabs are not links. It suggests `cursor: default` is more suitable for non-link tab elements.

References:
- [Buttons shouldn't have a hand cursor – Adam Silver](https://adamsilver.io/blog/buttons-shouldnt-have-a-hand-cursor/)
- [CSS 2.1 User Interface](https://www.w3.org/TR/CSS2/ui.html#propdef-cursor)

**Comment by ryo-manba** [comment]
Thanks for the discussion! However, it appears that the current CSS specification is still in the Editor's Draft stage. It will be some time before it becomes an official recommendation, but can we use this draft as a basis? This is my simple question.

**Comment by mcking65** [comment]
@ryo-manba asks:

> Thanks for the discussion! However, it appears that the current CSS specification is still in the Editor's Draft stage. It will be some time before it becomes an official recommendation, but can we use this draft as a basis? This is my simple question.

For normative changes to the specification, we would not ordinarily base decisions on a draft that is early in the spec process. However, since this doesn't appear to be normative guidance and since it does not require user agent changes, then it seems safe, and likely best, to follow the guidance in the draft referenced by @jugglinmike.

If you find evidence that suggests a different course of action is better, please let us know by reopening this issue.
