### ISSUE TITLE
Update table Style in example template

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#328]
Group decided to add the full grid lines based on decision at https://www.w3.org/2017/03/13-aria-apg-minutes.html

**Comment by MichielBijl** [comment]
The CSS can be simplified to:

```
table.attributes tbody th,
table.attributes tbody td {
    border: 1px sold silver;
}
```

There is nothing in the base.css (W3C default style) that prevents borders on specific elements. We only care about tables with the `.attributes` class; this is the class applied to all role / attribute tables.

**Comment by mcking65** [comment]
@MichielBijl, so, I will merge pull #329 since it has the desired effect. However, we will leave this issue open so that either you or James can take care of the implementation detail of simplifying the CSS. My understanding from today's meeting is that you would make this change. So, assigning this issue to you.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria-practices/commit/e389a15c91c0d2f529cfd35015b108bd3ec99159
