### ISSUE TITLE
Navigation Menu Button Example should use a button element for the menu button

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-practices#352]
The [Navigation Menu Button Example](http://w3c.github.io/aria-practices/examples/menu-button/menu-button-links.html) shows a menu button containing a menu of links.
For some reason, the button itself ("WAI-ARIA Quick Links") uses an `<a>` element and adds a role of "button", but this does not seem correct to me - I think it should just use a button element.
The test of whether or not to use an anchor element is this: "Will the user ever want to open this thing in a new browser tab or window?" If the answer is, "No", then it does not make sense to use an element that can be right-clicked and have the browser's context menu contain items such as: "Open link in new tab", "Open link in new window", etc. Please just use a button element for the "WAI-ARIA Quick Links" button.
(The menu items are ok as links - it is only the menu button that should not be a link).

**Comment by mcking65** [comment]
@MichielBijl, were you planning on submitting a PR for this? If so, could it be before Oct 18?

**Comment by MichielBijl** [comment]
@mcking65 this was never assigned to me? But I can do it.

**Comment by MichielBijl** [comment]
Fixed in https://github.com/w3c/aria-practices/commit/9714cf4138ce609187bdb2d6ba694b7fd6679a49

**Comment by mcking65** [comment]
@MichielBijl, thanks!

I am reopening though because we still have to align the documentation on the page with the code. There is some language in the intro that needs to be edited because it mentions the button. There is also a row that needs to be removed from the states and props table and some additional rows where the element column needs to be changed from `a` to `button`.

Do you have time for this too?

**Comment by mcking65** [comment]
Commit 9597648 wraps this up.
