### ISSUE TITLE
Tabs example page links to wrong section of main document

### ISSUE THREAD

**Issue by JasonTarka-D2L** [w3c/aria-practices#391]
The [Tabs example page][1] has a link, "design pattern for tabs.", that links to [the Checkboxes section][2], when it should link to [the Tab section][3].

[1]: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs.html
[2]: https://www.w3.org/TR/wai-aria-practices/#checkbox
[3]: https://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by mcking65** [comment]
@JasonTarka-D2L, thank you for the feedback.

This is fixed in the editors' draft. See the 
[example of tabs with automatic activation](http://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html) 
and the 
[example of tabs with manual activation](http://w3c.github.io/aria-practices/examples/tabs/tabs-1/tabs.html).
