### ISSUE TITLE
Navigation Menu Button Examples: Unreachable code in PopupMenuLinks.js

### ISSUE THREAD

**Issue by racer2207** [w3c/aria-practices#396]
`  while (childElement) {
    var menuitem = childElement.firstElementChild;
    if (menuitem && menuitem === 'A') {
      throw new Error(msgPrefix + 'has descendant elements that are not A elements.');
    }
    childElement = childElement.nextElementSibling;
  }`

Line 53 of PopupMenuLinks.js

I believe the conditional statement will never equal true since menuitem is an element and not a string. Wouldn't this work better?

` if (menuitem && menuitem.tagName !== 'A') {`

**Comment by mcking65** [comment]
@racer2207, thank you for catching this and providing a detailed description of the problem.

@jongund, thank you for implementing the fix.

It's almost embarrassing this sat unfixed for more than a year, but it is now fixed in commit 8bc433e, which is landed in master. It will be published to w3.org in release 2 of APG 1.1 in mid July.
