### ISSUE TITLE
Menubar examples: Make mouse behaviors and parent menu item appearance change triggers more consistent with desktop conventions

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#408]
The following two problems with the 
[editor menubar example](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html) 
and the [navigation menubar examples](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html) 
were raised in issue #144.

#### Problem 1 described by @carmacleod in issue #144:

> When moving a mouse horizontally across a menubar, hovering over each menu button to see what is in its menu, 
> each newly-opened menu appears instantly (good) 
> but the previously-open menu hesitates before closing, 
> which looks like both menus are open for a while, which feels really odd. 
> This odd behavior does not happen when I use right/left arrow keys to traverse through the menus.

#### Problem 2 described by @carmacleod in issue #144:

> Using either keyboard or mouse, when the user opens a menu and then traverses to a menu item inside that menu, 
> the menu button in the menubar no longer looks selected. 
> For example, open the Font menu, and arrow down to the Serif menu item. 
> The selected look of the Font menu button disappears. 
> This is different from the look of a desktop menubar, which would show the Font menu button as "pushed in" (for Windows menubars) or "blue" (for Mac menubars) 
> while the Font menu is open.

#### Consensus resolution documented in issue #144

Agreement on the following mouse behaviors is documented in issue #144.

1. Open menus remain open if the user moves the mouse away; remove timeouts that close menu when the mouse moves away.
2. Mouse behaviors that cause an open menu to close are:
    A. User clicks anywhere outside the menu. 
    B. User clicks an action item in the open menu.
    C. User hovers over a different parent menu item in the menubar, triggering display of that parent's submenu.
3. Submenus open on hover over a parent item in the menubar only if another submenu is already open. That is, if all submenus are closed, a click on a parent menu item is required to display a submenu.

The task force also agrees to the behavior proposed by @carmacleod to resolve problem 2 described above. A parent menu item should retain it's activated appearance while its submenu is open.

**Comment by carmacleod** [comment]
The above commit fixes the [menubar-2 example (Editor Menubar)](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html).
If you like these changes, then I will fix the [menubar-1 example (Navigation Menubar)](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html).
I can also have a look at the Menu Button examples to see if any of the changes are applicable.

**Comment by mcking65** [comment]
The fix can be seen in RawGit at:
https://rawgit.com/carmacleod/aria-practices/issue408/examples/menubar/menubar-2/menubar-2.html

**Comment by carmacleod** [comment]
The above commit fixes the issue noted by @sh0ji that simply hovering over a menubar item should not focus the item. However, please note that if a menubar or any of its components already has focus, hovering needs to move the focus so that keyboard commands continue to work as expected.

For example, if a menu is open and another menubar item is hovered, the previous menu closes, the new menu opens, and arrow keys are expected to work in the new menu and not the old.

I verified this behavior in the Windows 7 Notepad menubar and the MacOS menubar. In all cases, hovering on menubar items that have open menus, and also on menuitems in open menus, causes the focus to move to the hovered item so that further keyboard input is directed there.

Please keep this in mind when testing this latest commit.
I tested with JAWS/Chrome and NVDA/Firefox.

**Comment by mcking65** [comment]
@carmacleod, My interpretation of the feedback from @sh0ji, @jnurthen, and others was that there are good accessibility reasons for the hover behavior of menubars on the web to depart from the hover behavior of desktop menubars. While some desktop menubars do move focus on hover, on web moving focus in response to hover is conceptually similar to an automatic change of context; it has the same kinds of negative side effects. It may even be argued that desktop menubars would be more assistive technology friendly if they did not move focus in response to hover.

If I am mistaken on this point, I am sure @sh0ji, @jnurthen, @jongund, @annabbott, or others will chime in.

**Comment by carmacleod** [comment]
@mcking65 Yes, I'd love to hear from others about it. Would be interesting to know what the concerns are, and why it's different from desktop.

I am surprised to hear that desktop menubars could be more assistive technology friendly. The Windows desktop menubar seems pretty decent, as long as you know to type ALT to get to it. Mac OS menubar is admittedly a bit less friendly due to having to remember to type CTRL+F2 (or FN+CTRL+F2 depending on your function key setting). However, they both have the same hover behavior.

Note that I did initially try to fix the menubar-2 example so that focus didn't move on hover at all, but that made keyboard behavior feel "quite broken". Unexpected things would happen. For example, I could hover over a menuitem, which made it look "selected", and so I expected that typing down arrow would move the selection down to the next menuitem, but it actually closed the open menu, opened an old one, and then moved down. Quite startling.

We are in a grey area where we are mixing keyboard and mouse. The desktops have been there before, which is why I look to them for behavior choices.

Remember that a menubar is one tab stop. So keyboard handling needs to either be managed with activedescendant, or managing tabindex and moving focus. This example uses the latter method, which is arguably more robust for browsers and assistive technologies; for example, the browser will handle scrolling a focused item into view without the author having to worry about that.

I _could_ (don't shoot me - just a suggestion ;) turn off the outline, and then the user would never know that focus is being moved. Let me know if you want to try that - it can be achieved with the following css:
```
ul[role="menubar"] *:focus {
  outline: none;
}
```

Please, everyone, give this latest commit a try. If possible, go back and forth from mouse to keyboard, and compare to [the original behavior](http://w3c.github.io/aria-practices/examples/menubar/menubar-2/menubar-2.html) as well.

Matt, can you please do your rawgit magic to create a testable link? (Note that there is one more commit - I found and fixed a bug this morning).

**Comment by mcking65** [comment]
The most recent proposed resolution can be reviewed using this rawgit link to the issue408 branch in Carolyn's fork:
https://rawgit.com/carmacleod/aria-practices/issue408/examples/menubar/menubar-2/menubar-2.html

**Comment by jongund** [comment]
I believe we need to follow web behaviors in terms of mouse behaviors, and so we should not have mouse hover change focus in the menubar examples.

**Comment by sh0ji** [comment]
My feedback in the PR is relevant here: https://github.com/w3c/aria-practices/pull/593#issuecomment-368616588

**Comment by carmacleod** [comment]
As @katiehockman said in #598:
> In native apps, it is common that mouse interactions like hover work together with the arrow keys to navigate a menu. So if someone were to hover the mouse over a menu item, then press the down arrow, it would be expected that the keyboard interaction picks off where the hover interaction left off.

> The implementation that I am mentioning is the one which Google Docs and the Chrome menu both use. In those cases, hovering over a menuitem within a menu _does_ change the browser focus. The user would have had to explicitly click or press enter on the menu button or menu item to open the menu, but once inside, the hover and arrow keys work together to navigate the menu.

**Comment by carmacleod** [comment]
Taking ownership of this in order to fix up the odd mouse and timeout behavior in the menubar-1 example (Navigation Menubar) in a similar manner to what was done for the menubar-2 example (Editor Menubar) in PR https://github.com/w3c/aria-practices/pull/593.

**Comment by carmacleod** [comment]
This issue is completely fixed by @jongund's recent update of the Navigation Menubar Example in https://github.com/w3c/aria-practices/pull/1359. Thank-you, @jongund !

Closing.
