### ISSUE TITLE
2.7 Checkbox  -> WAI-ARIA Roles, States, and Properties

### ISSUE THREAD

**Issue by devarshipant** [w3c/aria-practices#454]
http://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/#checkbox

Under 'WAI-ARIA Roles, States, and Properties' --

One of the list items read:

>The checkbox has an accessible label, preferably provided by a visible label associated using aria-labelledby.

Note that using only aria-labelledby does not give additional clickable area to mouse users. There are other valid techniques to create programmatic relationships besides labelledby.

**Comment by MichielBijl** [comment]
Nice catch! Especially since the code examples use a child text node as their label.

**Comment by mcking65** [comment]
@devarshipant, thanks for the feedback!

We will address this when we resolve closely related issue #456.

Since an ARIA checkbox is not built with an input element, I am not sure what you are saying about clickable area. The labeling technique is not going to effect that since you can use any element you wish to define the clickable area. Your labeling choices for an ARIA checkbox are content, aria-labelledby, and aria-label. The only advantage to the content approach is that you could do it all with a single div.

I am closing this as a duplicate, but feel free to comment further either here or in 456.

**Comment by devarshipant** [comment]
@mcking65 -- thanks for looking into this:

Clickable area is the additional area users get when selecting the control (checkbox, in this case). For instance, clicking the label of the checkbox selects the control. 

My original observation was that suggesting aria-labelledby as a **preferred** technique to create programmatic association may mislead readers to think that they can get by using aria on form controls. There could be a blowback when mobility impaired users, who benefit from that additional click area, find it difficult to select the control. A hybrid use of for / id and aria, with for / id tying up the checkbox label and its control, and labelledby associating the pattern label (group caption) and checkbox label to the control, might serve us better in that bullet.
