### ISSUE TITLE
Why does ARIA Detail Message Dialog (role=alertdialog) need a role=document tabindex=0 & focus() on detail message?

### ISSUE THREAD

**Issue by pauljadam** [w3c/aria-practices#48]
http://www.w3.org/TR/wai-aria-practices-1.1/#alertdialog

I tried it like it recommends for this demo http://pauljadam.com/demos/detail-message-dialog.html but it did not work and actually broke VoiceOver OS X usage so I had to do it like normally where you set focus to the first logical button inside the dialog and no role=document or tabindex=0. 

So basically my demo is going against the spec but I was trying to follow the spec but it did not work as expected. 

Thanks!

**Comment by mcking65** [comment]
@pauljadam, thank you for the feedback!!

The document role inside the message dialog is completely unnecessary, and we will remove that guidance.

I haven't yet had a chance to look with a OS X system, so I am curious to see what effect it had on VoiceOver. There may be a VoiceOver bug because this shouldn't break VO in any way; embedding a document role inside a dialog, while unnecessary, is a valid construct.

I'll take a look at your example implementation on my macbook when I have an opportunity.

Closing this per comment added to issue #54.

**Comment by pauljadam** [comment]
Hi Matt, thanks for taking a look! I wrote a fairly long blog post on this pattern, it should help explain my thoughts, http://www.deque.com/blog/aria-modal-alert-dialogs-a11y-support-series-part-2/
