### ISSUE TITLE
Review Disclosure Design Pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#493]
The [Disclosure Design Pattern](http://w3c.github.io/aria-practices/#disclosure)
is ready for its final task force review.

#### Reviews Requested as of October 23, 2017

- [x] Review by Ann (@annabbott)
- [x] Review by Siri (@shirsha)
- [x] Review by James (@jnurthen)

**Comment by annabbott** [comment]
No issues noted in the Design Pattern.

**Comment by shirsha** [comment]
Please see my suggestions:

- Add "the" infront of the visibility:
A disclosure is a button that controls  **the** visibility of a section of content. 

- Content is spelled wrong.
 When  the controlled conted  (instead of **content** ) is hidden, 

- Missing hype after right in the text "right pointing"

it is often styled as a typical push button with a right **-** pointing arrow or triangle to hint that activating the button will display additional content.

**Comment by mcking65** [comment]
@shirsha, thank you for the review. Made corrections with commit c0a55ba. Didn't add "the" before "visibility" though; it is not necessary.

**Comment by jnurthen** [comment]
I've seen comments on twitter that they don't like the name disclosure. 
https://twitter.com/pauljadam/status/929095509905731585

Expandable was another suggestion. How about adding it in parentheses after.

**Comment by mcking65** [comment]
@jnurthen, that is already in place. The title is:

> 3.9 Disclosure (Show/Hide)

I like show/hide much better than expandable; it is far more descriptive.

**Comment by mcking65** [comment]
It appears work is done; all reviews are complete and comments are addressed. Thank you to everyone who contributed! Closing.
