### ISSUE TITLE
menuitemradio and menuitemcheckbox select on Space shouldn't be optional

### ISSUE THREAD

**Issue by katiehockman** [w3c/aria-practices#587]
https://www.w3.org/TR/wai-aria-practices/#menu
"
Space:
(Optional): When focus is on a menuitemcheckbox, changes the state without closing the menu.
(Optional): When focus is on a menuitemradio that is not checked, without closing the menu, checks the focused menuitemradio and unchecks any other checked menuitemradio element in the same group.
"

There should be some way for someone to select a menuitem without closing the menu every time. From a usability perspective that would be incredibly frustrating to have to keep opening the menu after every selection.

**Comment by katiehockman** [comment]
Just noticed that this was intentionally changed to be optional per https://github.com/w3c/aria-practices/pull/339. Does the fact that this has been moved to 1.1 APG Release 2 mean this decision to be optional is being re-evaluated?

**Comment by jnurthen** [comment]
@katiehockman this was simply triaging the issue. No decision has been made on whether there needs to be a change. Like any issue it will be looked at - but we have not yet evaluated this one.

**Comment by mcking65** [comment]
@katiehockman commented:

> There should be some way for someone to select a menuitem without closing the menu every time. From a usability perspective that would be incredibly frustrating to have to keep opening the menu after every selection.

We discussed this in our [January 29, 2018 meeting](https://github.com/w3c/aria-practices/wiki/January-29%2C-2018-Meeting).

The task force agrees that in scenarios where checking multiple menuitemcheckbox elements is a likely use case, that this could be frustrating. 

However, the behavior described for the Space key in the pattern is marked optional because:

1. Native menus do not support it.
2. It is consequently not easily discoverable.
3. It does not have a mouse equivalent.

Because of the value that it could provide to keyboard efficiency in some circumstances, the TF agreed to leave the optional behavior in the pattern.

However, precisely because menus close when menuitems are activated, a menu is not typically a good choice for scenarios that require a multi-select check lists.

**Comment by StommePoes** [comment]
I have some confusion, esp with `menuitemcheckbox` in particular.

> Native menus do not support it.

I can't think of a native menu with checkboxes in them? Or do you mean, desktop application menus that have checkboxes in them (I still can't think of any)?

> It is consequently not easily discoverable.

How discoverable is space on checkboxes anywhere else? The reason we're thinking of user frustration is because sighted keyboarders see a checkbox and think "oh those work with spacebar". That it's inside a menu, I'm not sure if it's in a goat or in a boat or anywhere else-- the control and how it's announced seems to be what's suggesting how it works, no?

> It does not have a mouse equivalent.

Same with checkboxes? What is the mouse equivalent of spacebar on a checkbox?

**Comment by patrickhlauke** [comment]
> I can't think of a native menu with checkboxes in them? Or do you mean, desktop application menus that have checkboxes in them (I still can't think of any)?

They're not super common, but for instance: in Firefox, View > Zoom > Zoom Text Only (can be ticked/unticked - but not with SPACE, just ENTER)

**Comment by patrickhlauke** [comment]
and regarding the mouse behavior: just like a regular menu item, selecting a checkbox or radio button in a native application menu checks it, but also closes the menu altogether

**Comment by mcking65** [comment]
The task force decision to-date for release 2 is to keep the optional space key behavior in the pattern because it can have useability value once discovered. As mentioned by @StommePoes, there is a discoverability problem. If we revisit this decision, the most likely outcome is to remove space key from the pattern.

I'm closing this issue. Anyone may feel free to re-open if they wish to add reasons for reconsideration.
