### ISSUE TITLE
Inappropriate use of the hidden attribute?

### ISSUE THREAD

**Issue by mindplay-dk** [w3c/aria-practices#601]
I've been following the example for accessible tabs here:

https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html

In this example, the `hidden` attribute is used to hide the tab-panels.

[Section 7.1](https://www.w3.org/TR/2011/WD-html5-20110525/editing.html#dom-hidden) of the HTML 5 spec specifically states:

> it is incorrect to use `hidden` to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation

Presumably there is a more approriate way to hide tab panels?

**Comment by jnurthen** [comment]
This text is no longer present in the HTML spec. See the current Editor's draft at http://w3c.github.io/html/editing.html#the-hidden-attribute

I am unsure exactly when it got removed but it was not correct advice.

Please close if this resolution is satisfactory.

**Comment by mcking65** [comment]
@mindplay-dk, please feel free to re-open with comments if the response from @jnurthen is not sufficient.

**Comment by mindplay-dk** [comment]
> I am unsure exactly when it got removed but it was not correct advice.

Thanks for the clarification 👍

**Comment by remmythical** [comment]
Huh, apparently that sentence [is still in the living standard](https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute) and also [was there when this issue was opened in the first place](http://web.archive.org/web/20180201061526/https://html.spec.whatwg.org/multipage/interaction.html)?

(I'm not sure if the link posted by @jnurthen has lead to a different draft that i can't find anymore, currently it only redirects to the page linked above.)

The sentence is directly under the first example.

> The hidden attribute must not be used to hide content that could legitimately be shown in another presentation. For example, it is **incorrect to use hidden to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation** — one could equally well just show all the form controls in one big page with a scrollbar. It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked hidden, it is hidden from all presentations, including, for instance, screen readers.

I'm currently implementing a tab navigation with hidden panels and was also really confused by the contradiction from the HTML spec (and mdn page) and the wai-aria examples, which is how i found this issue.

Can this issue get re-opened? Is this an issue with the html spec?

**Comment by JAWS-test** [comment]
I would say that it is an error of the HTML spec

**Comment by jnurthen** [comment]
Thanks - I must have missed it when I posted the link. I agree with @JAWS-test that is is an issue in the HTML spec

**Comment by jnurthen** [comment]
https://github.com/whatwg/html/issues/4904

**Comment by JAWS-test** [comment]
For pure text browsers that can neither interpret Javascript nor CSS, <code>display:none</code> would be better than <code>hidden</code>, because they could then display the hidden content.

**Comment by ZoeBijl** [comment]
@JAWS-test ideally you’d add tabs via progressive enhancement. Which would negate the issue.

**Comment by mcking65** [comment]
Duplicated by #1197

Closed by #1198
