### ISSUE TITLE
Two-State Checkbox Example: Missing group label

### ISSUE THREAD

**Issue by katiehockman** [w3c/aria-practices#604]
#### Fix plan added by @mcking65

In the [two-state checkbox example](https://www.w3.org/TR/wai-aria-practices/examples/checkbox/checkbox-1/checkbox-1.html),
add `role="group"` to the div that wraps the `<ul>` and `aria-labelledby` pointing to the H3 to label the group.

Do not change the tri-state example referenced in the following original report; it uses fieldset/legend to label the group.

### Original report from @katiehockman

In both of the W3C examples, the checkbox group is missing a label. This conflicts with the APG which states "If a set of checkboxes is presented as a logical group with a visible label, the checkboxes are included in an element with role group that has the property aria-labelledby set to the ID of the element containing the label."

The two examples missing labels:
https://www.w3.org/TR/wai-aria-practices/examples/checkbox/checkbox-1/checkbox-1.html
https://www.w3.org/TR/wai-aria-practices/examples/checkbox/checkbox-2/checkbox-2.html

**Comment by mcking65** [comment]
Interesting ... good catch @katiehockman.

At one time I recall having that on the first example, but it is no longer there.
I remember having the labeled group present because we had been contrasting it with the second one, the [mixed state example](https://www.w3.org/TR/wai-aria-practices/examples/checkbox/checkbox-2/checkbox-2.html).
Another reason why we need regression testing in place ... it is coming.

The mixed state example uses fieldset/legend in lieu of a labeled group.
However, the design pattern says nothing about native alternatives to labeled groups; so, that is a separate issue.

I'm not going to try and dig up the history; we'll just fix it.
