### ISSUE TITLE
Landmarks section should include advice that all content should be in a landmark.

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#637]
Migrating old tracker issues
https://www.w3.org/WAI/ARIA/track/issues/505

**Comment by carmacleod** [comment]
All *perceivable* content. Wrapper divs and hidden things don't count.  :)

**Comment by jnurthen** [comment]
Also Skip to main content link need not be in a landmark - as if you are using landmarks to navigate there is no need to have it.

**Comment by jnurthen** [comment]
> Skip links should also be in a landmark. Usually the closest is the header element.

@MichielBijl Why? Who does this help? If someone is navigating by landmarks they can already do the functionality provided by the skip link. If someone is not navigating by landmarks then it doesn't matter if they are in a landmark or not.
Am I missing a use case where having a skip link within a landmark actually makes the page better for anybody?

**Comment by MichielBijl** [comment]
@jnurthen, I would like to invite @stevefaulkner to the conversation. This is something I learned from him.

**Comment by carmacleod** [comment]
> Skip links should also be in a landmark. Usually the closest is the header element.

Adding skip links to the banner or closest nav is ok if those already exist. I just wouldn't want to encourage authors to go _creating_ new navs to put skip links in, because that would increase the number of landmarks for no useful reason (nobody is going to navigate to a "skip links" landmark in order to then "Skip to main", for example... they would navigate directly to the main landmark instead).

> All content is perceivable no? A wrapper-div wouldn’t count as it itself isn’t content. I would think it’s fine to leave out some hidden things such as <script>-tags.

Hidden content isn't perceivable, which includes closed dialogs, panels, tooltips, menus and the like, plus any of the tags, like `<script>`, that are hidden in the [browsers' default style sheet](https://www.w3.org/TR/html5/rendering.html#hidden-elements):

> [hidden], area, base, basefont, datalist, head, link, meta, noembed, noframes, param, rp, script, source, style, template, track, title, input[type=hidden], and noscript if there's script.

About wrapper-divs, the reason I singled them out is because an automated tool that I use flagged wrapper divs as needing to be in a landmark. I disagree, so I opened a bug against the tool.  :)  I think it would be nice if it was explicitly stated somewhere that wrapper divs are transparent to the user, so they don't need to be contained in a landmark. Of course, if they have perceivable content (i.e. non-hidden descendents), then that content needs to be in a landmark.

As for hidden things that become visible... they would need to be in a landmark, although some of those things, like open menus and visible tooltips, are so transient that they cannot be navigated to, so I wonder about those. Also, I don't have an answer for dialogs. For non-modals, the user would very likely want to navigate to/from the dialog. Maybe they should be in a separate region. Modals are harder. When a modal is present, I would think that all of the other landmarks should become non-navigable. Should the modal itself be in a separate region? Should it be a child of the region it was invoked from? I don't know.

**Comment by carmacleod** [comment]
Ok. I think the migrated-in issue is fixed already, because the [current landmark section](http://w3c.github.io/aria-practices/#general-principles-of-landmark-design) says:
> Including _all content_ on a page in one of its landmark regions and giving each landmark region a semantically meaningful role is one of the most effective ways of ensuring assistive technology users will not overlook information that is relevant to their needs.

The only thing I might change is to use the phrase _all perceivable content_ instead of _all content_.

Although, step 1, immediately following, does say:
> Break the page into _perceivable areas of content_ which designers typically indicate visually using alignment and spacing.

So maybe it's good enough as-is, but personally, I would still prefer to hammer home the "perceivable" bit, for the benefit of test tooling as well as authors.  :)

> We do not address anti-patterns in the APG

Interesting. I hadn't thought about it before, but it makes sense. I guess there would just be way too many... ;)

**Comment by stevefaulkner** [comment]
The general rule is 'all content inside a landmark' as content outside of a landmark can be missed if it is orphaned (outside of a landmark). 
[Rich Schwerdtfeger wrote (2013): ](https://developer.paciellogroup.com/blog/2013/02/using-wai-aria-landmarks-2013/#comment-806)
> Probably the most important rule for applying landmarks is to ensure all content resides in a landmark region to ensure no content is orphaned. This way a screen reader user can safely use landmark navigation without missing content. This practice will be in the next working draft release of the WAI-ARIA authoring practices(editor’s draft).

**Comment by carmacleod** [comment]
@stevefaulkner What would you say about custom tooltips? Dialogs? There was some discussion about these in a few of the comments above.

**Comment by mcking65** [comment]
With commit 7123db1, added "perceivable" as suggested. Considering this now complete.
