### ISSUE TITLE
Listbox: How to make a collapsible listbox required?

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#657]
The collapsible listbox https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html is based on button. How can this be set to be required as button does not support aria-required. 
The best I can think of is to set the child listbox to required but this doesn't really satisfy the desire to mark the button itself as required.

**Comment by zelliott** [comment]
Wondering if there has been any update on this front?

**Comment by zelliott** [comment]
Bump on this again. Wondering what the guidance is on using aria-required with a popup listbox?

**Comment by ZoeBijl** [comment]
@mcking65 any updates on this? Currently `aria-required` isn’t allowed on the `button` element (or the `button` role for that matter).

Should ARIA add something like a `select` role that encompasses this entire widget? It does seem odd that doesn’t exist. But we have something similar with the tabs design pattern. But I digress. @jnurthen any thoughts?

**Comment by mcking65** [comment]
Now that we have rewritten combobox for ARIA 1.2, the [new combobox pattern](http://w3c.github.io/aria-practices/#combobox) can be used instead of a collapsable listbox. In fact, you could use almost the same code as the collapsable listbox except that the element that is the button would become the combobox element. There would be a few other changes too, but most of the mechanics would be the same.

If the 1.2 draft of combobox ends up in the final spec, then we would be able to remove the collapsable listbox example and replace it with a select-only combobox example, which would resolve this issue.

**Comment by zelliott** [comment]
Thank you for the update mcking65.

**Comment by scottaohara** [comment]
since the new combobox pattern has been published, should this pattern be removed per @mcking65's comment above?

**Comment by smhigley** [comment]
I volunteer as tribute to make a PR to remove it 😄
