### ISSUE TITLE
In Accordion CONTROL+PageUp doesn't work in chrome

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#671]
The Accordion example says this.

> Control + Page Down | When focus is inside an accordion panel or on an accordion header, moves focus to the next accordion header.When focus is on last accordion header or inside last accordion panel, moves focus to first accordion header.
-- | --
> When focus is inside an accordion panel, moves focus to the header for that panel.When focus is on an accordion header, moves focus to the previous accordion header.When focus is on first accordion header, moves focus to last accordion header.

But in Chrome 65 CTRL+PageUp (or down) changes browser tab forwards and backwards.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

Also, In JAWS the arrow keys just go into the accordion content inside the heading, not to the next heading.

**Comment by jnurthen** [comment]
See https://stackoverflow.com/questions/15094920/prevent-default-ctrl-pageup-and-ctrl-pagedown-in-chrome

**Comment by DaveBagler** [comment]
@jnurthen, the author of that stack overflow question gave up and added a key to the shortcut to make it work. The only response mentions the mouse wheel event issue, but that issue was fixed in 2014. Have you been able to make the CTRL+PageUp/Down work (cross-browser) without adding a modifier?

@DavidMacDonald, have you found a solution to this issue?

**Comment by mcking65** [comment]
Closing as duplicate of #400.
