### ISSUE TITLE
Breadcrumb trail underlines on live links verses no underline

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#685]
The breadcrumb pattern has no discussion about visible identification of links vs no visible indication.

https://www.w3.org/TR/wai-aria-practices-1.1/#breadcrumb

I think there should be a discussion about why or why not they should be visibly identified as links. 

WCAG does not require groups of links to be visibly identified with underlines or other visible indication  on each link because the block itself and it's placement is sufficient visible identification. However, WCAG requires links that are in a block of text to be visibly identified to distinguish them from the surrounding text. Some have proposed that breadcrumb trails where the active page is **_not_** a link need to have underlines on the active links to distinguish the inactive link from the active link.

I would say that is not necessary because the user is on that page already and the section is primarily a block of links which under WCAG doesn't require any additional visual indicators on links. A breadcrumb trail is very easily visually identifiable and it has emerged on the web primarily as a pattern that doesn't have underlines on the links.

I would like to propose a paragraph discussing this and a conclusion that the underlines are optional on active links in a breadcrumb trail. I can write up that paragraph and make a pull request if there is general agreement.

The [example]( https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html) could also be updated.

**Comment by jnurthen** [comment]
IMO WCAG is the right place for this discussion not ARIA practices. The discussion isn't about the ARIA part of the example.

**Comment by DavidMacDonald** [comment]
hmmm... true.... perhaps just remove the underlines then? At least then it's not giving the idea that the links are part of the model.

**Comment by mcking65** [comment]
@DavidMacDonald, the task force would accept a pull request that only removes the underlines from the breadcrumbs. We believe the example is acceptable wither with or without the underlines. If you decide to submit a PR, please reference this issue.

However, we do not want to include a paragraph that details reasons for and against underlining in breadcrumbs. We want to be careful not to replicate WCAG guidance in the APG. We have a couple places that reference WCAG; they do not explain WCAG since that is not the role of the APG.

I'm closing this issue. Please re-open if you do not believe the resolution is satisfactory.
