### ISSUE TITLE
Add guidance for blockquote, caption, and paragraph roles

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria-practices#700]
w3c/aria#761 added `blockquote`, `caption`, and `paragraph` roles as part of role parity with HTML. We need these roles added to authoring practices.

#### Preview Link

The latest version of the section covering this issue is available in the
[structural roles section of APG 1.2 in Rawgit](https://rawgit.com/w3c/aria-practices/apg-1.2/aria-practices.html#structural_roles)

**Comment by jnurthen** [comment]
I propose a section such as the following

## Roles intended for parity with HTML

Most authors should not use roles from this section when adding ARIA to HTML documents and instead use the equivalent native html elements. They are in the ARIA specification to allow creation of web components which have the same behaviours as native HTML controls.

@@ why is this different to button?? - ideally we would not use role=button either @@

### blockquote
A section of content that is quoted from another source.

### caption
On-screen descriptive text for a figure or table in the page.

Authors SHOULD reference the element with role caption by setting aria-describedby on the figure or table.

### parapgraph
A paragraph of content.

@@ we should flesh out the descriptions rather than just copying from the ARIA spec @@

@@ should we add examples - IMO we should but would we end up sending people down the wrong path if we did.... we really don't want people to use these with HTML@@

**Comment by mcking65** [comment]
@jnurthen, please have a look at the latest version at:
https://rawgit.com/w3c/aria-practices/apg-1.2/aria-practices.html#structural_roles

**Comment by mcking65** [comment]
Considering complete with commit bd0bfce. Closing and opening up to broad review with review issue 739.
