### ISSUE TITLE
Menubar: link on the first level

### ISSUE THREAD

**Issue by iamryanyu** [w3c/aria-practices#725]
Hi there,

On this example,
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/menubar/menubar-1/menubar-1.html

The "Enter" and "Space" key is to open the submenu accordion to the keyboard support section for the Menubar. However, if the first menu itself has a link (such as About, Admissions, Academics), shouldn't the "Enter" key actually trigger the link?

If not, how can I trigger the link for the first level menu with the keyboard?

Thanks a lot in advance!

Warm regards,
Ryan

**Comment by mcking65** [comment]
@iamryanyu, 

Yes, enter would open the link and down arrow would open the submenu. There is a note about that in the pattern in the keyboard section. While we know that it is common to overload parent menu items with link behavior, we don't recommend it. It is far better to put the link inside the submenu. This is particularly important for touch because there is no way to open the submenu if tapping the parent activates  a link. It is also not very obvious to screen reader users that enter will activate a link. So, they may be very surprised when Enter does not move focus into the submenu.

Nevertheless, per issue #159, we plan to one day develop a version of the example that has this behavior.

Please feel free to re-open this issue if this does not sufficiently answer your question.

**Comment by MrMagooThis** [comment]
Hello,

I am a newbie to web-development, and even more so with ARIA compliance.

I have 3 questions:

**#1**
I am referencing a couple of places which I believe deal with ARIA menubars:
https://www.w3.org/TR/wai-aria-practices/#menu
https://www.w3.org/WAI/tutorials/menus/application-menus-code/

Are both of these sights good places to use for understanding ARIA menubars?  Being a newbie, I am a bit confused where to start with understanding how to make my sight ARIA compliant.  For my project, I am inclined to use the first link above as it seems to be similar to the Bootstrap 4 Navbar that I have based my project on.

I am confused on why the examples for the meubar would not be located in one location.


**#2**
My project has a navigation menu bar at the top of the web page and while it has drop-down menus that contain menuitems with clickable links, I also have clickable links directly on the navigation menu bar.  For those items, would it be more appropriate that those items be something like a button, because the examples referenced above do not appear to execute a link (menuitem) directly on the menubar as it does in a sub-menu?

Example:
I copied what I consider to be a clickable link from a sub-menu and re-purposed it to the menubar.  (The FoxNews menuitem)

https://jsfiddle.net/MrMagoo/jh5sfkdo/

Therefore, reading the ARIA documentation at https://www.w3.org/TR/wai-aria-practices/#menu, 
I believe that the FoxNews link should be a button instead of a menu item?  Does that sound correct?  And in my example code, it would be better to place FoxNews to one side of the navigation menubar as opposed to in the middle which would break up the flow of navigating the menubar with the keyboard.


**#3** 
Again with my project based upon the Bootstrap 4 Navbar

(https://getbootstrap.com/docs/4.1/components/navbar/#responsive-behaviors)

Instead of one  `<ul>` , I have 2 `<ul>` elements...one for menubar items located to the left-side, and the other on the right-side of the menubar.

The Bootstrap 4 example shows a form located to the right-side of the navigation menubar, but I replaced that with the 2nd `<ul>`.  Is that a bad design method on my part if I want to be ARIA compliant?  

If so, I guess that I could get all drop-down menus located under one `<ul>` and then place the buttons in a form in the other location as Bootstrap has done.

Thank you in advance for your time answering my questions, or suggest where it would be more appropriate to ask such questions.

Sincerely,

Mike
