### ISSUE TITLE
Review Alert Dialog Example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#736]
With many thanks to @sh0ji, development of the [alert dialog example](http://w3c.github.io/aria-practices/examples/dialog-modal/alertdialog.html)
for issue #101 is complete.

#### Reviews requested as of June 24, 2018

- [ ] Review by James (@jnurthen)
- [x] Review by Ann (@annabbott) 
- [ ] Review by Siri (@shirsha)

**Comment by annabbott** [comment]
Found a nit: in the sentence "Activating the "yes" button removes the contents of both the "Notes" text area and local storage of the notes ." remove the extra space between the last word in the sentence and the period.

**Comment by annabbott** [comment]
Neither Save nor Discard button function in IE11 using kbd or mouse.

**Comment by annabbott** [comment]
Tested using Firefox 60.0.2 and Chrome Version 67.0.3396.99 with JAWS 2018.1805.33 and NVDA 2018.1.1 on Win10:: works as designed.

**Comment by robfentress** [comment]
Could you provide an alternative example where `aria-hidden` is used to hide content outside of the alert dialog when the dialog is open.  At least with your [combobox](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox) examples you do provide an alternative that is designed to work with older AT because support for the ARIA 1.1 implementation isn't there yet.
