### ISSUE TITLE
Combobox examples: missing description about the id attribute

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#785]
The description for row `id="string"` in the textbox `Role, Property, State, and Tabindex Attributes` table is unclear to me.

It says "Referenced by `for` attribute of `label` element to provide an accessible label." 

The second two examples do no have a "for" attribute on their "label" elements, they instead have "aria-labelledby" on their textbox.

**Comment by mcking65** [comment]
Potentially related to issue #542.

**Comment by carmacleod** [comment]
I had a look at this issue, using the preview links from PR https://github.com/w3c/aria-practices/pull/1276:
* [Preview combobox autocomplete=both](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-both.html)
* [Preview combobox autocomplete=list](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-list.html)
* [Preview combobox autocomplete=none](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-none.html)

All 3 examples now use an HTML label with a `for` attribute, so there's no longer any use or mention of `aria-labelledby` (which is good).

However, the "Role, Property, State, and Tabindex Attributes" table no longer lists the `id` for the combobox's text input.

Perhaps it should? Maybe something similar to the `id` row in the [grid-combo example](https://w3c.github.io/aria-practices/examples/combobox/grid-combo.html):


Role | Attribute | Element | Usage
-- | -- | -- | --
combobox | id="string" | input[type="text"] | - Referenced by `for` attribute of `label` element to provide an accessible name. - Recommended naming method for HTML input elements because clicking label focuses input.

@spectranaut Would adding that row help clarify the 3 previews from PR https://github.com/w3c/aria-practices/pull/1276?

**Comment by zcorpan** [comment]
Fixed in https://github.com/w3c/aria-practices/pull/1276
