### ISSUE TITLE
Broken links in examples

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/aria-practices#786]
Doing a link check for the 1.2 FPWD, I found links broken in examples. Some of them may be intentional for example purposes, and some may be relative links that didn't work out when moved to TR, but most of them are links that I think can and should be fixed.

https://www.w3.org/TR/2018/
error code: 403 (forbidden request), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/listbox/listbox-collapsible.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/alertdialog.html
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/alert.html

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/index.html
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/combobox/aria1.0pattern/js/combobox-1.0-listbox.js
error code: 300 (ambiguous), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.eot
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.eot?
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.svg
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.ttf
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.woff
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.woff2
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

https://www.w3.org/TR/wai-aria/introduction
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html

https://www.w3.org/TR/wai-aria/roles
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html

https://www.w3.org/TR/wai-aria/states_and_properties
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html

https://www.w3.org/TR/wai-aria/usage
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html

mailto:aaron@thegoogle.rocks
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:billy@dangerous.fish
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:doris@rufflazydogs.sleep
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:issie@imadeadcatsadly.wascute
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:joe@blahblahblah.blahblah
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:kitten@kittenseason.future
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:someone@please-do-it.company
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

**Comment by mcking65** [comment]
@michael-n-cooper,

This one mystifies me:

https://www.w3.org/TR/2018/
error code: 403 (forbidden request), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/listbox/listbox-collapsible.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

The only reference to w3.org on those pages is for the style sheet. And, that URI exactly matches the same on many other example pages. Do you have any idea what the source of the error may be?

**Comment by mcking65** [comment]
@michael-n-cooper, Here's what I've been able to do so far. I think this is all I can do before we publish the note. I hope this is sufficient.

#### Fixed links

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/alertdialog.html
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/alert.html
Fixed with commit be6562c.

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/alert/index.html
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/
Fixed with commit 168bcd9.

https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/combobox/aria1.0pattern/js/combobox-1.0-listbox.js
error code: 300 (ambiguous), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
Fixed in commit 541bdf9.

https://www.w3.org/TR/wai-aria/introduction
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html
Fixed with commit 7a80757.

https://www.w3.org/TR/wai-aria/roles
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html
Fixed with commit 7a80757.

https://www.w3.org/TR/wai-aria/states_and_properties
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html
Fixed with commit 7a80757.

https://www.w3.org/TR/wai-aria/usage
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/grid/LayoutGrids.html
Fixed with commit 7a80757.

#### Not fixed

Can't find this link on pages where it failed:
https://www.w3.org/TR/2018/
error code: 403 (forbidden request), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/listbox/listbox-collapsible.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

Will have someone help resolve; unsure of what is needed.
https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.eot
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

Will have someone help resolve; unsure of what is needed.
https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.svg
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css
https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.ttf
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

Will have someone help resolve; unsure of what is needed.
https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.woff
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

Will have someone help resolve; unsure of what is needed.
https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/fonts/glyphicons-halflings-regular.woff2
error code: 404 (not found), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/landmarks/css/bootstrap.css

#### Must we fix these?

The following mailto links are demo links in an example treegrid. Do we have to make them functional?

mailto:aaron@thegoogle.rocks
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:billy@dangerous.fish
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:doris@rufflazydogs.sleep
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:issie@imadeadcatsadly.wascute
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:joe@blahblahblah.blahblah
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:kitten@kittenseason.future
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

mailto:someone@please-do-it.company
error code: 12007 (no such host), linked from page(s):
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=start
	https://www.w3.org/TR/2018/WD-wai-aria-practices-1.2-20180719/examples/treegrid/treegrid-1.html?cell=force

**Comment by mcking65** [comment]
I believe this is resolved. We will have another link check in the upcoming publication soon to be certain.
