### ISSUE TITLE
Review Treegrid Example

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#790]
The [editor's draft of the treegrid example](http://w3c.github.io/aria-practices/examples/treegrid/treegrid-1.html)
developed for issue #132 is complete.
Because of the complexity of this example, the APG task force is seeking broad community feedback with its inclusion in APG 1.1 Release 2 and encourages anyone who may reference this example to follow this issue and any subsequent updates made to the editor's draft of the example page referenced in this issue.

Please provide feedback about the functionality or documentation of this example by commenting on this issue.

#### Known issues

[ ] Issue #789: Some focus rectangles overlap neighboring cells.

**Comment by devarshipant** [comment]
- NVDA 2018.1 and Chrome 68:

1. There is no association with the table header when focus is on a gridcell.
2. Speaks the level number and expanded state.
3. Missing instructions on using arrow keys to navigate.
4. Should the treegrid with table headers be navigable using table quick key?


- JAWS 2018 and Chrome 68:

1. There is association with the table header when focus is on a gridcell, except the first header Subject.
2. Speaks expanded state, not the level.
3. Missing instructions on using arrow keys to navigate.
4. JAWS recognizes the table and allows quick key navigation (T).
5. Changes cursor mode (to Virtual) when JAWS encounters the link throwing off arrow navigation.

**Comment by spectranaut** [comment]
I'm almost writing regression tests for this example. This is really good work! :)

There are only two places where the documentation is unclear. Both are for `tabindex` in the "Role, Property, State, and Tabindex Attributes" table:
* in the `tabindex="-1"` row 
  * It says: "All row and gridcell elements are focusable, but only one is included in the tab sequence." 
  * This is not exactly true, gridcells do not have `tabindex="-1"` but rather no tabindex set. When there is an interaction with the treegrid that should move focus to that gridcell, the gridcell will get `tabindex='0'`. If focus moves from the gridcell, it will go back to having no tabindex. In a semantic way, all gridcells are "focusable", but I think that using "focusable" semantically might be misleading (because you cannot call focus on them nor send keys to them unless they are already in focus).
* in the `tabindex="0"` row
  * It says: "Only one row or gridcell in the treegrid has tabindex="0".
  * this is not true. A row and a gridcell can both have `tabindex="0"` at the same time. If you focus on the first row, the last gridcell (really, the link instead the last gridcell) also has `tabindex="0"`. This happens on other rows as well. Additionally, if you focus on the first or second gridcell, that gridcell and the last gridcell have `tabindex="0"`

**Comment by spectranaut** [comment]
There is one bug in this example. The ENTER key should trigger the mail to link when the focus is on the email in last column.  If you click on the link, it opens email as expected.

To replicate:
- Tab to the email in the first row
- Hit the ENTER key
   - Bug: nothing happens

**Comment by mcking65** [comment]
@devarshipant commented:

> * NVDA 2018.1 and Chrome 68:
> 
> 1. There is no association with the table header when focus is on a gridcell.
> 2. Speaks the level number and expanded state.
> 3. Missing instructions on using arrow keys to navigate.
> 4. Should the treegrid with table headers be navigable using table quick key?

1 is either NVDA or Chrome bug. 3 is an NVDA bug. 4 is up to NVDA team, but it would seem to be an appropriate expectation. In the context of the aria-at project, we would probably categorize 4 as a should have feature, but then confirm that with NVDA team.

> * JAWS 2018 and Chrome 68:
> 
> 1. There is association with the table header when focus is on a gridcell, except the first header Subject.
> 2. Speaks expanded state, not the level.
> 3. Missing instructions on using arrow keys to navigate.
> 4. JAWS recognizes the table and allows quick key navigation (T).
> 5. Changes cursor mode (to Virtual) when JAWS encounters the link throwing off arrow navigation.

I think these are all JAWS bugs.

Note that measuring and tracking screen reader support levels is the domain of the [w3c/aria-at](https://github.com/w3c/aria-at ) project. We will have a prototype of the infra for that project by mid November.

**Comment by mcking65** [comment]
Issues to capture required changes have been opened. Thank you for the feedback.
