### ISSUE TITLE
Accordion Example: Restructure to remove `dl` element

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#815]
As discussed in w3c/html-aria#110, due to a recent change, the ARIA in HTML spec does not currently allow role presentation on `dl`, heading on `dt`, or region on `dd`. As a result, the [accordion example](http://w3c.github.io/aria-practices/examples/accordion/accordion.html) does not validate.

While the APG TF would like to see the ARIA in HTML spec changed to allow retrofitting of existing content, it does agree that an accordion can be made using less ARIA markup with a different set of HTML elements and that doing so would better illustrate appropriate use of ARIA. This issue calls for the accordion example to be changed to use a `div` for the container, heading elements for the headings, and `section` elements for the panels. This will also mean that a note should be added to state that if the author does not want the panels to be landmark regions, that the section elements should be replaced with div elements.

### To-do

- [ ] Land commit to fix accordion structure
- [ ] Remove validation override for dl/dt/dd from .vnurc

**Comment by Decrepidos** [comment]
‘if the author does not want the panels to be landmark regions, that the section elements should be replaced with div elements.’. 

As the region is only announced when the accordion section is expanded—what accessibility issues would this cause?  If negligible would it need the <div> option?

**Comment by accdc** [comment]
I'm not clear on the use of section and how this relates to the ARIA Accordion design pattern. As far as I understand we are not, and should not be, saying that within the APG that authors have to use specific HTML elements to achieve proper ARIA usage, because it's impossible to predict how authors will have to implement ARIA in all cases.

For example, what if an author has to create an accordion that does not use section elements and they cannot. How will this pattern show the proper syntax of ARIA usage to make this accessible?

The role=region aspect is important in this latter case, and also when dealing with nested accordions. Omiting the use of regions in such cases makes it impossible to reliably identify proper nesting structures and associated boundaries.

**Comment by Decrepidos** [comment]
In case it helps I set up an accordion with different design patterns.
[https://www.a11ycats.com.au/aria-testing/](url)

**Comment by Decrepidos** [comment]
In case it helps I set up an accordion with different design patterns.

https://www.a11ycats.com.au/aria-testing/
