### ISSUE TITLE
Bug in example menubar/menubar-1/menubar-1.html (key SPACE and ENTER)

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-practices#907]
In the [menubar-2 example](https://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html), the documentation in the Keyboard Support table for Submenu say the following about the ENTER and SPACE keys:
* Activates menu item, causing the link to be activated.
* NOTE: the links go to dummy pages; use the browser go-back function to return to this menubar example page.

When the focus is on a menuitem that has a submenu attached to it (for example, the "facts" item in "About" dropdown), both ENTER and SPACE open the submenu instead of the link.

**Comment by jongund** [comment]
@mcking65 

What should happen here?   Should sub menuitems with popups follow links or open popup menus, like the menuitems in the menubar?

**Comment by carmacleod** [comment]
@spectranaut Ok to close this issue?

The latest version of the [Navigation Menubar Example](https://w3c.github.io/aria-practices/examples/menubar/menubar-navigation.html) says the following for Space/Enter on Submenu items:

- If the item is a parent menu item, opens submenu and moves focus to first item in the submenu.
- Otherwise, activates menu item, which navigates to a dummy page. NOTE: use browser go-back function to return to this page.
