### ISSUE TITLE
Draft tree grid design pattern

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#91]
When working on this issue, there is some old content that may be useful in the file aria-practices-DeletedSectionsArchive.html.

The relevant section can be seen here:
https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#treegrid

**Comment by wendyabc** [comment]
Tree Grid isn't in the new draft. What's the plan for it returning in future drafts? This is a pattern we rely on and use quite a lot.

**Comment by mcking65** [comment]
@wendyabc  wrote:

> This is a pattern we rely on and use quite a lot.

You are just the person I was hoping would show up! Perhaps you can help? Do you have functional, accessible treegrids?

Completing the treegrid pattern is in the Authoring Practices Task Force milestone plan for the version of ARIA Authoring Practices that will be published when ARIA 1.1 becomes a recommendation. That said, I am not 100% confident we will have it baked by then. There are quite a few issues to work out with treegrid.

The ARIA 1.0 treegrid pattern referenced above was deleted because following it would be problematic.

* It contains keyboard guidance that appears to be both incomplete and unconventional, e.g., ctrl+right to expand. 
* The roles, states, and properties guidance is also incomplete and contains guidance regarding aria-readonly that is not consistent with ARIA 1.1 clarifications about the meaning of aria-readonly in the grid context.
* It refers to two examples, neither of which are accessible.

**Comment by aleventhal** [comment]
I can help work on this. 

I need this now for an accessible tool I'm developing called automation inspector, for inspecting the Chrome Automation API. It uses a 3rd party library for the treegrid called FancyTree, which has good keyboard + ARIA for regular trees, and makes an attempt at access for treegrids.

**Comment by aleventhal** [comment]
CC'ing @robdodson and @surma

Here is a proposal:
- left/right for collapse expand because that is by far what is most expected among users for trees.
- the keystroke for move by word on the given platform to move between columns (ctrl+left/right on windows, alt+left/right on mac). I believe there have been implementations that have done this before in mail clients, I'll check into it.
- Ideally, a screen reader should begin reading from the current cell to the end of the given row.
Worst case, if a user does not discover the command to move by cell, they will still be able to move by row, expand/collapse, and hear all the information available. The move by cell command which is harder to know about is helpful for reducing the amount of TTS, but not as important.

Screen readers may not do the "read to the end" behavior automatically. Therefore, may be advisable to have the entire row focused when the user is focused on the first column. That would allow us to get most of the behavior we need in today's screen readers.

**Comment by aleventhal** [comment]
Here are more detailed thoughts on the design pattern and an example:
https://github.com/aleventhal/treegrid-example

**Comment by aleventhal** [comment]
I decided that move-by-word isn't as discoverable as it needs to be. Instead, the user can tab to active cells in the current row with the tab key.
Here's an example of this:
https://github.com/aleventhal/treegrid-tab-active-cells 
Screen readers would use the built-in table navigation feature of their AT to navigate non-interactive cells.

**Comment by jongund** [comment]
I submitted a draft as pull request 714

**Comment by annabbott** [comment]
Design pattern > Left arrow > fourth bullet currently is:
If focus is on a first cell in the row and row focus is not supported,focus does not move.

Edit necessary: add space after comma:
If focus is on a first cell in the row and row focus is not supported, focus does not move.

**Comment by annabbott** [comment]
Design pattern > Left arrow > fifth bullet currently is:
If focus is on a any other cell, focus one cell to the left.

Edit necessary: remove 'a' between 'on' and 'any':
If focus is on any other cell, focus one cell to the left.

**Comment by annabbott** [comment]
Design pattern > Control + Space > second bullet currently is:
If focus is on a call, selects the column that contains the focus.

Edit necessary: change 'call' to 'cell':
If focus is on a cell, selects the column that contains the focus.

**Comment by annabbott** [comment]
Design pattern > WAI-ARIA Roles, States, and Properties > fourth bullet > second sentence currently is:
Set to aria-expanded to false when the child rows are in a closed state and set to true when the child rows are in an open state. 

Edit necessary: remove 'to' as second word in that sentence:
Set aria-expanded to false when the child rows are in a closed state and set to true when the child rows are in an open state.

**Comment by annabbott** [comment]
Design pattern > WAI-ARIA Roles, States, and Properties > fourth bullet > third sentence currently is:
End rows cannot have the aria-expanded attribute because, if they were to have it, they would be incorrectly described to assistive technologies as parent nodes. 

What is an 'end row'? Is it a 'last row'? Or a 'bottom row' as mentioned previously? Needs clarification...

**Comment by annabbott** [comment]
Design pattern > WAI-ARIA Roles, States, and Properties > eleventh bullet currently is:
If the treegrid supports selection, when a cell or row is selected, the selected element has aria-selected set true. 

Edit necessary: add 'to' before 'true':
If the treegrid supports selection, when a cell or row is selected, the selected element has aria-selected set to true.

**Comment by annabbott** [comment]
Design pattern > WAI-ARIA Roles, States, and Properties > twelfth bullet > first sentence currently is:
If the treegrid provides content editing functionality and contains cells that may have edit capabilities disabled in certain conditions, aria-readonly may be set true on cells where editing is disabled.

Edit necessary: add 'to' before 'true':
If the treegrid provides content editing functionality and contains cells that may have edit capabilities disabled in certain conditions, aria-readonly may be set to true on cells where editing is disabled.

**Comment by annabbott** [comment]
Design pattern > WAI-ARIA Roles, States, and Properties > twelfth bullet > second sentence currently is:
If edit functions are disabled for all cells, aria-readonly may be set true on the grid element.

Edit necessary: add 'to' before 'true':
If edit functions are disabled for all cells, aria-readonly may be set to true on the grid element.

**Comment by annabbott** [comment]
No further issues noted.

**Comment by mcking65** [comment]
Thank you @annabbott, I have made the corrections in commit 73eea9d.

**Comment by mcking65** [comment]
This issue is now complete and the pattern is ready for wide review. :) Closing!
