### ISSUE TITLE
ARIA 1.1 Combobox with Listbox Popup Examples - Mouse Hover style vs key board selection style

### ISSUE THREAD

**Issue by gaurav5430** [w3c/aria-practices#983]
In the first example,
Hovering over an option and selecting an option using keyboard are two different actions which mean different things, but the UI indication for both of them is the same color.

If selected using keyboard, and pressed TAB:
the keyboard selected option is the current value

if hovered using mouse and pressed TAB:
nothing happens

if hovered using mouse, and then keyboard up/down:
does not take into account the current hovered element.

So, in all it seems that the currently hovered element is not selected, but since the UI indication is the same, it looks like it is.
Should the UI indication be different?

**Comment by carmacleod** [comment]
This issue will be fixed after PR https://github.com/w3c/aria-practices/pull/1276 is merged, because the PR styles items differently for hover and focus.

@ZoeBijl Are the new item focus/hover styles ok from a visual design perspective?
* [Preview combobox autocomplete=both](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-both.html)
* [Preview combobox autocomplete=list](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-list.html)
* [Preview combobox autocomplete=none](https://raw.githack.com/w3c/aria-practices/issue1066-combobox-fix-escape-key-and-other-bugs/examples/combobox/combobox-autocomplete-none.html)

**Comment by mcking65** [comment]
Thank you @carmacleod, linking this issue to #1276.
